### ISSUE TITLE
Unable to install linux libraries for OpenCV

### ISSUE THREAD

**Issue by nsankar** [aws/studio-lab-examples#10]
@EmilyWebber I am not able to install the following libraries (for opencv) due to permission issues. How to install it.

!apt update
!apt-get install -y libglib2.0-0 libsm6 libxrender1 libxext6

![image](https://user-images.githubusercontent.com/431890/144620939-e471f7fb-ebb8-4458-89ba-69025d64f3b7.png)

**Comment by samx18** [comment]
Currently Studio Lab doesn't support package linux installs that require root access. You can install python packages via conda and pip.

**Comment by EmilyWebber** [comment]
Also, here is a tutorial for installing open-cv in Docker containers.

https://programmerah.com/installing-opencv-python-in-docker-container-15489/
