### ISSUE TITLE
Add clear explanation about the influence of Anaconda’s Terms of Service to Studio Lab conda environment to FAQ

### ISSUE THREAD

**Issue by icoxfog417** [aws/studio-lab-examples#100]
**Is your feature request related to a problem? Please describe.**
(This issue propose the updating [FAQ](https://studiolab.sagemaker.aws/faq) not Studio Lab itself.)

There is a concern about [Anaconda’s Term of Service](https://www.anaconda.com/terms-of-service) influences Studio Lab `conda` environment. In that case, users should take care that their usage of Studio Lab corresponds to commercial activities or not.

To relieve the concern of users, We should add clear explanation about the influence of Anaconda’s Terms of Service to Studio Lab `conda` environment to FAQ.

**Describe the solution you'd like**
Add the following question and answer to  [FAQ](https://studiolab.sagemaker.aws/faq) not Studio Lab itself).

Q: The Anaconda’s Terms of Service influences conda in Studio Lab?

No. We build Studio Lab conda from [mini-forge](https://github.com/conda-forge/miniforge) distribution and pull from [conda-forge](https://conda-forge.org/) by default. The conda-forge is [not influenced from term of service](https://conda-forge.org/blog/posts/2020-11-20-anaconda-tos/). The term of service will influence only when you install libraries from [Anaconda default channel](https://docs.anaconda.com/anaconda/user-guide/tasks/using-repositories/). 

**Describe alternatives you've considered**
This description on this issue may be the alternative to FAQ. But official FAQ should answer users’ concern.

**Additional context**
If you have questions about this topic, please let us know by comments. We want to relieve your concern as possible.

**Comment by MicheleMonclova** [comment]
Hi - we will be updating this in our FAQ soon.

**Comment by icoxfog417** [comment]
The FAQ was updated. I close the issue.

```
Q: How does Studio Lab use Conda?
All examples that are provided with Studio Lab leverage Conda which is a free and open source library. Customers that want to leverage other libraries, such as Anaconda, are responsible for their own licensing with those 3rd parties.
```
