### ISSUE TITLE
Assigning IAM Role to Studio Lab instance?

### ISSUE THREAD

**Issue by cloudchampions** [aws/studio-lab-examples#104]
Hi, I'd like to assign an IAM Role to my Studio Lab instance and call Comprehend with boto3.

I can't find support for this in the Lab documentation. Please advise.

**Comment by ioanfr** [comment]
Inside Studio Lab you can configure connection to your AWS account using credentials as explained in [this notebook](https://github.com/aws/studio-lab-examples/blob/main/connect-to-aws/Access_AWS_from_Studio_Lab.ipynb). After installing boto3 library you can call Comprehend APIs directly from Studio Lab. As a prerequisite you also need to allow your corresponding AWS IAM user to call Comprehend. Under IAM user you can attach an existing Comprehend policy or add a custom Comprehend inline policy.
