### ISSUE TITLE
Example notebook with localstack

### ISSUE THREAD

**Issue by SoumayaMauthoorMOJ** [aws/studio-lab-examples#106]
**Is your feature request related to a problem? Please describe.**
I want to be able to test my notebook locally and share my notebook without necessarily having access to AWS resources

**Describe the solution you'd like**
An example of how to run a notebook against AWS resources created using localstack, with the option to run the notebook against an AWS account if provided

**Describe alternatives you've considered**

**Additional context**

**Comment by icoxfog417** [comment]
@SoumayaMauthoorMOJ Thank you for your feature request. I understand you try to test your Jupyter Notebook that includes AWS resource access (such as S3) without the actual AWS account. [LocalStack](https://localstack.cloud/) seems to be very useful. I figured out LocalStack required docker that Studio Lab does not have (and can not install by `apt install` because `sudo` is not allowed). If you have experience and have idea to execute LocalStack without docker, please let me know.

**Comment by SoumayaMauthoorMOJ** [comment]
@icoxfog417 apologies for the delay I was away on holiday. It's possible to install [LocalStack](https://localstack.cloud/) [natively](https://medium.com/testvagrant/how-to-install-localstack-natively-on-ubuntu-18-04-step-by-step-ca344b7b7d78) but it's a bit of pain. The alternative is to give the user the option to run/test the notebook locally against a dockerised LocalStack instance, and use aws .config and .credentials to switch between running against LocalStack and AWS. I'm happy to look into this myself if you think it would be a useful example? I  should have some time next weekend.

**Comment by icoxfog417** [comment]
@SoumayaMauthoorMOJ Of course, I prepared the example notebook. That was a little complex procedure, so that I'm glad if you try this example and after that feedback to me. It'll be helpful for other developers.

https://github.com/icoxfog417/localstack-lab

**Comment by SoumayaMauthoorMOJ** [comment]
@icoxfog417 thanks for the quick response! Still technically on holiday so will test this weekend

**Comment by SoumayaMauthoorMOJ** [comment]
I did some testing and would like to make some suggestions but I don't think I have permission to create a new branch on the repo, can you please add me to it?

**Comment by icoxfog417** [comment]
@SoumayaMauthoorMOJ , Thank you for your test! You can fork my repository by clicking the "Fork" button and send the modification as Pull Request to my repository.

![image](https://user-images.githubusercontent.com/544269/168023026-04e08595-4390-4a66-bbf4-d507dd8608b1.png)

If you do not familiar with sending the Pull Request, please refer the following video etc.

* [Creating a pull request](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request)
* [Creating a Simple Github Pull Request (video)](https://www.youtube.com/watch?v=rgbCcBNZcdQ)

**Comment by SoumayaMauthoorMOJ** [comment]
Hello @icoxfog417 apologies for the delay , pull request has now been raised :-)

**Comment by icoxfog417** [comment]
@SoumayaMauthoorMOJ Thank you for pull request! I merged it!
