### ISSUE TITLE
Open the GitHub repository by Studio Lab link

### ISSUE THREAD

**Issue by icoxfog417** [aws/studio-lab-examples#11]
**Is your feature request related to a problem? Please describe.**

When I study machine learning from the [GitHub repository that contains multiple `.ipynb` files](https://github.com/tirthajyoti/Machine-Learning-with-Python), I have to open a file one by one because the [Studio Lab link](https://github.com/aws/studio-lab-examples/tree/main/open-in-studio-lab) only allows opening the individual files.

**Describe the solution you'd like**
![image](https://user-images.githubusercontent.com/544269/144705358-59ed1579-b1b6-424b-a60a-4fa66927b030.png)

**Describe alternatives you've considered**
To put the Studio Lab button to each Jupyter notebook. But it is redundant work for the repository maintainer.

**Additional context**
This feature will be necessary to add Studio Lab to [Jupyter Book](https://jupyterbook.org/intro.html), which is used to write the [various machine learning books](https://executablebooks.org/en/latest/gallery.html). (I tried to add Studio Lab link to Jupyter Book and [found the discussion](https://github.com/executablebooks/sphinx-book-theme/pull/385#issuecomment-924756477) that suggests the necessity of the above feature..)

**Comment by samx18** [comment]
Thanks for checking out Studio lab. How about cloning the repository from Studio lab instead? Does that help? Studio Lab supports git integrations and cloning. Perhaps include instructions in the README of your repo to clone it via Studio lab?

**Comment by icoxfog417** [comment]
Dear samx18, thank you for your reply! 

I confirmed that I can select copy `.ipynb` or clone the entire repository on the popup window.
When selecting the clone, `git clone` runs. It's sufficient for me and the Studio Lab users. 

1. Open in SageMaker
2. Start runtime
3. Copy to Project
4. Copy from GitHub?
5. Select "Clone Entire Repo"
6. Clone Git Repository
7. Clone

When I want the users to clone the entire repository, I want to point out `README.md` in the GitHub repository.
[From the document](https://github.com/aws/studio-lab-examples/tree/main/open-in-studio-lab#1-find-the-url-for-your-file-hosted-on-github), I assume that the Studio Lab link allows a markdown file but when opening the `README.md` causes the error.

The following link causes the error.
https://studiolab.sagemaker.aws/import/github/aws/studio-lab-examples/blob/main/README.md

![image](https://user-images.githubusercontent.com/544269/144738434-1a8a3195-552e-43f1-a024-71a78aa998df.png)

**Comment by adalseno** [comment]
I don't know if this helps but if you clone the repo locally 

```
(studiolab) studio-lab-user@default:~/sagemaker-studiolab-notebooks$ mkdir tmp_project
(studiolab) studio-lab-user@default:~/sagemaker-studiolab-notebooks$ cd tmp_project/
(studiolab) studio-lab-user@default:~/sagemaker-studiolab-notebooks/tmp_project$ git clone https://github.com/tirthajyoti/Machine-Learning-with-Python.git
```

then you can open the file using the markdown preview like this:
![Schermata 2021-12-06 alle 20 05 55](https://user-images.githubusercontent.com/2405291/144906852-0662a66c-3651-4446-b996-3e04fb41d0a1.png)

And it will open the markdown:
![Schermata 2021-12-06 alle 20 06 06](https://user-images.githubusercontent.com/2405291/144906891-f728072f-a31c-47ca-9bef-b3fc31971ec5.png)

**Comment by EmilyWebber** [comment]
Yes - you can both clone the repo locally and use the UI through the button to clone the entire repository. The instructions were incorrect - currently only ipython notebooks are supported to open via the button, and markdown files are not. If you like, you can open an issue in the feature request format to request this. 

https://github.com/aws/studio-lab-examples/blob/main/.github/ISSUE_TEMPLATE/feature-request-for-sagemaker-studio-lab.md

Thanks for trying SM Studio Lab!
