### ISSUE TITLE
Account request denied

### ISSUE THREAD

**Issue by bekahose** [aws/studio-lab-examples#112]
hello, my mail yandex.com

The answer has come.

Account request denied

Unfortunately, your request for an Amazon SageMaker Studio Lab account was denied. Your email is associated with activity that may have violated our Terms of Service

sincerely,

— The Amazon SageMaker Studio Lab team

Do you not accept yandex mail?

Why was I not accepted?

**Comment by MicheleMonclova** [comment]
Hi Bekahose,
I cannot say for certain why your request was denied, but try an email with a different domain. Let me know how that goes.
Thanks!
Michele
