### ISSUE TITLE
more gpu options

### ISSUE THREAD

**Issue by huawdinho** [aws/studio-lab-examples#116]
Add more gpus good for machine learning, example: tesla p4, p100, v100

this will fix gpu runtime error and help everyone at same time with more gpus.

**Comment by icoxfog417** [comment]
@huawdinho Thank you for your idea! If you like https://github.com/aws/studio-lab-examples/issues/98, please 👍 to this issue to measure the needs of the community.

**Comment by icoxfog417** [comment]
Dea @huawdinho thank you for your good idea! I close this issue to avoid the duplication.
