### ISSUE TITLE
Can't install Ta-lib

### ISSUE THREAD

**Issue by icematerial** [aws/studio-lab-examples#119]
Hi,

I want to use Ta-lib library, but can't install in  SageMaker Studio Lab.

I use below code for it.

!curl -L http://prdownloads.sourceforge.net/ta-lib/ta-lib-0.4.0-src.tar.gz -O && tar xzvf ta-lib-0.4.0-src.tar.gz
!cd ta-lib && ./configure --prefix=/usr && make && make install && cd -
!pip install ta-lib

And below error
~~~~~
ERROR: Command errored out with exit status 1:
   command: /home/studio-lab-user/.conda/envs/default/bin/python3.9 -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-wo2rl6eg/ta-lib_24117cb7e2bf4a0ba3de5cd078a8a0a9/setup.py'"'"'; __file__='"'"'/tmp/pip-install-wo2rl6eg/ta-lib_24117cb7e2bf4a0ba3de5cd078a8a0a9/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-yjgib16k
       cwd: /tmp/pip-install-wo2rl6eg/ta-lib_24117cb7e2bf4a0ba3de5cd078a8a0a9/
  Complete output (28 lines):
  /tmp/pip-install-wo2rl6eg/ta-lib_24117cb7e2bf4a0ba3de5cd078a8a0a9/setup.py:77: UserWarning: Cannot find ta-lib library, installation may fail.
    warnings.warn('Cannot find ta-lib library, installation may fail.')
~~~~~~~

How to use Ta-lib in SageMaker Studio Lab?
Please help me.
Thanks,

**Comment by icoxfog417** [comment]
@icematerial Thank you for using the Studio Lab. We can install `ta-lib` from conda. 

https://anaconda.org/conda-forge/ta-lib

Studio Lab is working based on conda environment so that installing the library from conda is preferable.

**Comment by MicheleMonclova** [comment]
Glad it is working. would you mind closing this issue?

**Comment by icematerial** [comment]
Sorry

**Comment by icematerial** [comment]
Sorry
