### ISSUE TITLE
Install node.js and npm

### ISSUE THREAD

**Issue by adalseno** [aws/studio-lab-examples#12]
**Is your feature request related to a problem? Please describe.**
It's both a feature request and a problem:
I would like to install this jupyterlab extension https://github.com/jupyter-server/jupyter-resource-usage but it needs node.js and npm and I could not find a way to install them in SageMaker Studio Lab since I cannot get root privileges

**Describe the solution you'd like**
A think that pre-installing node.js and npm would be a good idea (they are required by several jupyterlab plugins)

**Describe alternatives you've considered**
Allow sudo

**Additional context**
This is not related to the above, but it's annoying: I also had issues when I tried to download some files from the notebook. When the size is huge, in my case 600 Mb, the system gets stuck and the only way is closing everything, browser included, and restart from scratch. Small files can be downloaded without any issue. For the rest, the first impression is absolutely amazing!

**Comment by adalseno** [comment]
Solved! 
`conda install -c conda-forge nodejs`

**Comment by samx18** [comment]
Thanks for trying out SageMaker Studio Lab! I will go ahead and close this.
