### ISSUE TITLE
Access denied when signing up although I got the approve email

### ISSUE THREAD

**Issue by chelouche9** [aws/studio-lab-examples#120]
Hi, 

A few days ago I requested access to Sagemaker Studio Lab. Today I received an email approving my request, for some reason when trying to sign up I receive an error message:

 
<img width="431" alt="Screen Shot 2022-06-14 at 15 32 28" src="https://user-images.githubusercontent.com/71208698/173589737-540fbc7d-fde0-4cda-a285-82210a921729.png">

Any idea what should I do?

**Comment by MicheleMonclova** [comment]
this is interesting. What happens when you register?

**Comment by chelouche9** [comment]
I get the errors I posted above. The I am not approved yet

**Comment by MicheleMonclova** [comment]
It is true that our approves do expire after a couple of weeks. Please request an account a new,

**Comment by icoxfog417** [comment]
Dear @chelouche9 , can you get approval email? I hope you have already created the account. We are glad if you tell us the status of your problem.

**Comment by icoxfog417** [comment]
I will close this issue. Please feel free to raise a new issue if you still have the trouble.
