### ISSUE TITLE
Created account but when I try to login: “ This email or password didn't match our records.”

### ISSUE THREAD

**Issue by robptrck** [aws/studio-lab-examples#122]
**Describe the bug**

I created an account and activated it.

When I try to login I receive this message:

” This email or password didn't match our records. Please try again. Your account will be locked after 5 unsuccessful attempts.”

**To Reproduce**
Create a new account and see if this is repeatable. Someone else experienced a similar issue: https://repost.aws/questions/QUSB0wO0OiQ_irUdCx9ppjbg/registered-for-aws-sagemaker-studio-but-not-able-to-create-account 

MacOS, Safari and Chrome

**Comment by icoxfog417** [comment]
Dear @robptrck thank you for trying the Studio Lab and sorry for the late response. Do you still have the error? If so, please submit from the following form to confirm about your account.

https://pages.awscloud.com/GLOBAL_PM_PA_amazon-sagemaker_20211116_7014z000000rjq2-registration.html

**Comment by icoxfog417** [comment]
I close this issue because of the no response. Dear @robptrck , I hope your problem is solved. If you still have the problem, please let us know by another issue.
