### ISSUE TITLE
.bashrc file is not persistent in SMSL environment

### ISSUE THREAD

**Issue by austinlasseter** [aws/studio-lab-examples#123]
I'd like to use the Heroku CLI for pushing code to a Heroku git repository. I've installed the CLI on my SMSL instance (I wrote a post about how to do this, here: https://austinlasseter.medium.com/installing-the-heroku-cli-on-aws-sagemaker-studio-lab-6e53aaff1374).
Whenever I open a new SMSL session, I need to add heroku to $PATH each time, as follows. 
```
echo "export PATH=\$PATH:~/heroku/bin" >> ~/.bashrc
source ~/.bashrc
```

On a typical Linux instance, it's not necessary to do this repeatedly. Is there a way to ensure that my .bashrc will be persistent in SMSL? Thanks.

**Comment by icoxfog417** [comment]
@austinlasseter Thank you for writing the nice blog to connect Heroku! We can use `/home/studio-lab-user/.bashrc` instead `~/.bashrc`. I confirmed that the modification to `/home/studio-lab-user/.bashrc` is preserved after shutting down the instance.

**Comment by austinlasseter** [comment]
Thanks, this solved it.
