### ISSUE TITLE
Cannot download small dataset from Kaggle 

### ISSUE THREAD

**Issue by DCash02** [aws/studio-lab-examples#125]
Sent June 21, 2022 ~ 1500 PDT
Dear Staff:

Please explain why I get a 401 error when I try to download a relatively small dataset from Kaggle using the. Kaggle api. I am quite perplexed because the code has previously worked well  in another Jupyter notebook. If there is a sandbox in place, then provide the constraints under which we have  must comply. 
Thank you. 
/dan/
![image](https://user-images.githubusercontent.com/103302464/174902182-7aee7234-0918-46d1-9620-786a7bbe1c81.png)

**Comment by datanetai** [comment]
I can successfully download any dataset from kaggle. Can this solve your problem :https://github.com/Kaggle/kaggle-api/issues/279

**Comment by icoxfog417** [comment]
Thank you @datanetai to propose the solution!
@DCash02 , did the method from @datanetai work for you problem? If it works please let us know by closing the issue.

**Comment by DCash02** [comment]
Dear Ameer Hamza:

Thanks for your suggestion. That said, I am not having a problem with
Kaggle as I am using code that has worked for me in another Sagmaker
(Jupyter) notebook. Rather, the problem is that the code that has worked in
another Sagemaker account will not work when deployed in a notebook that
was created in Sagemaker Studio as a new notebook that generates a 401
error. Because the identical code worked error free  in another notebook,
this suggest that there is an undocumented  "sandbox"  contdrol adround the
notebooks in the "Sagemaker Studio Lab" which is distinguishable from a
standard Sagemaker "account"/ project.  Thanks again.
DC

**Comment by icoxfog417** [comment]
@DCash02 , you mean you faced 401 error in SageMaker Studio Lab but not occurred in SageMaker Studio despite you created the notebook same way?

**Comment by icoxfog417** [comment]
I close this issue because of no response. Dear @DCash02 , I you sill have 401 error in Studio Lab, please let us know by another issue.
