### ISSUE TITLE
Can't start any runtimes unfairly

### ISSUE THREAD

**Issue by pero03** [aws/studio-lab-examples#126]
**Describe the bug**
Error message "You can't use the project runtime because your account is associated with activity that may have violated our Service Terms"

**To Reproduce**
1. Go to 'CPU or GPU runtimes'
2. Click on 'Start runtime'
3. See error

**Expected behavior**
Successfully start the runtime and continue work sessions

**Screenshots**
![downloadsage](https://user-images.githubusercontent.com/107591632/175786098-619930f1-7195-4687-95a6-796f794e68c7.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro
 - Browser Microsoft Edge

**Additional context**
This issue has been very common recently and i don't know why, i was training my ML models and all of a sudden i can't get back on my sessions anymore, can you fix this? i believe that currently the system of the service is behaving weirdly cause it thinks that many users violated something when that's not true at all, most of the rules aren't even possible to be violated in the first place so why does this error occurs we need more fixing and explanations from the team thanks!

**Comment by xor-128** [comment]
Stop mining lol.

**Comment by pero03** [comment]
> Stop mining lol.

i don't get what you're talking about? i was training my ml models

also i don't think that's possible anyways and there isn't any users that can do it or have done it

the same weird message happened to some other people too you can look up the issue #117 thanks for your reply

**Comment by pero03** [comment]
it's basically an issue where while working at your project it decides to just stop

**Comment by icoxfog417** [comment]
Thank you for using Studio Lab @pero03 . We need to understand your situation. Could you please submit the following form to let us know about your account?

https://pages.awscloud.com/GLOBAL_PM_PA_amazon-sagemaker_20211116_7014z000000rjq2-registration.html

**Comment by huawdinho** [comment]
I'm having same problem, when i requested new account and tried use again sagemaker, after 2-3 hour got same error while jupyter lab was running.

**Comment by MicheleMonclova** [comment]
Please be careful that you are not violating cryptomining or hitting known domains associated with malware.

**Comment by icoxfog417** [comment]
@pero03 we close this issue. Please confirm your script do not violate the service term, and if you still have the trouble, please let us know.

**Comment by MicheleMonclova** [comment]
@huawdinho and @pero3, feel free to send me some information here: https://pages.awscloud.com/GLOBAL_PM_PA_amazon-sagemaker_20211116_7014z000000rjq2-registration.html.
Like @icoxfog417 mentioned, if we detect any violations or abuse we will shut your account down.  Make sure you are not hitting domains known for malware.  But if you feel you got this by mistake send me info and we will look into it.
