### ISSUE TITLE
new account waiting

### ISSUE THREAD

**Issue by horiovizzid** [aws/studio-lab-examples#129]
Hello. 
Are you not getting a new subscription?

It's been 10 days and still no mail etc.

**Comment by Armandbelucci** [comment]
Hello there,
I've been waiting for 8 days.

I sent 2 messages to this form. 2 days each

not even an answer.

I'm still waiting

**Comment by bekahose** [comment]
My account was approved after filling out the form.

**Comment by Armandbelucci** [comment]
Well I didn't even get an answer.

form not working anymore

**Comment by bekahose** [comment]
By the way, they don't serve Russia. if you are from russia your account will not be approved

**Comment by Armandbelucci** [comment]
no. i am in america

8 days is not too long for review.

**Comment by bekahose** [comment]
You should wait a little longer, maybe someone authoritative will write

**Comment by Armandbelucci** [comment]
ok thank you

**Comment by reddiclarewy** [comment]
hello I'm still waiting too.

is there any progress

**Comment by Armandbelucci** [comment]
no still waiting

**Comment by Armandbelucci** [comment]
they returned the form. that we are examining.

I'm texting again. They don't even answer.

hey amazon, anyone in charge?

**Comment by bekahose** [comment]
@icoxfog417

**Comment by Armandbelucci** [comment]
help please

**Comment by MicheleMonclova** [comment]
Hi Armandbelucci - did you get in yet?

**Comment by icoxfog417** [comment]
Dear @horiovizzid and all you are waiting the account approval, thank you for your patience for waiting. I hope your accounts are all approved. I close this issue, if you have not approved yet, feel free to raise a new issue. We are working to make the process fast at #99.
