### ISSUE TITLE
Account banned for no reason

### ISSUE THREAD

**Issue by aminhashemian** [aws/studio-lab-examples#130]
**Describe the bug**
when I want to start the runtime, I keep receiving the following message:
"You can't use the project runtime because your account is associated with activity that may have violated our Service Terms."

**To Reproduce**
1. open the login page and sign in
2. choose either CPU or GPU option
3. click on the 'Start Runtime' button
4. the error pops up

**Screenshots**
![image](https://user-images.githubusercontent.com/13276973/177843566-971d574c-25e9-4e73-9c87-a97f40c227bf.png)

**Expected behavior**
CPU/GPU runtime should start.

**Comment by MicheleMonclova** [comment]
Studio Lab has mechanisms to detect when accounts have violated their acceptable usages, (for example, crypto mining is not allowed).  Please review our FAQ to understand what you might have done to violate their service terms.

**Comment by aminhashemian** [comment]
Thanks for the response. Indeed I checked the Service Terms, and I am sure that I have not violated any of those terms of use. (I wasn't mining crypto, etc.) I was using the Sagemaker studio lab for my university thesis, where I am investigating NLP techniques for fact-checking the claims. Since I have not properly backed up my data from the Sagemaker studio lab, I still have some data that are essential for continuing my research, and I would be grateful if I could at least access my data, even if I am not allowed to use Sagemaker studio lab anymore.

> Studio Lab has mechanisms to detect when accounts have violated their acceptable usages, (for example, crypto mining is not allowed). Please review our FAQ to understand what you might have done to violate their service terms.
