### ISSUE TITLE
Can't connect to kernel nor execute anything.

### ISSUE THREAD

**Issue by ISDL29** [aws/studio-lab-examples#135]
After trying to make tensorflow work on AWS Studio Labs, I tried to uninstall it and intall it again using these 2 commands I found on [ internet](https://itsolutionpoints.com/question/keras-assertionerror-duplicate-registrations-for-type-experimentaloptimizer/):
> pip3 uninstall tensorflow absl-py astunparse flatbuffers gast google-pasta grpcio h5py keras keras-preprocessing libclang numpy opt-einsum protobuf setuptools six tensorboard tensorflow-io-gcs-filesystem termcolor tf-estimator-nightly typing-extensions wrapt
>pip3 install --no-cache-dir tensorflow

And then the console started to bug and I restarted the kernel.

After that the only kernel option is the default:python and when it tries to connect, it fails. I can't even execute anything, even console commands...

I stopped and resumed my runtime and the issue still prevails.

**Comment by icoxfog417** [comment]
Thank you for reporting your issue. That’s a very inconvenient issue that you can not run the notebook. Are there any error message when you connect to `default:python` kernel or launching the terminal? It will be the clue to resolve the issue, screen shot is also informative.  

As a first aid solution, we can propose to the following operations.

* Stop the instance and re-launch the instance (You already tried).
* Restart the JupyterLab

![image](https://user-images.githubusercontent.com/544269/180586123-78a12dcd-2ade-424e-a328-4ab8cef22ad3.png)

**Comment by ISDL29** [comment]
I restarted JupyterLab and the problem prevails. Once it shown me an error message but after that it never appeared again.

It just changes to No Kernel after I execute anything.

**Comment by icoxfog417** [comment]
Dear @ISDL29 , thank you for your reply. I hope bootcamp project is going well!

To delete your Studio Lab account and request account again is similar to factory reset. Your email is already approved so that waiting time for approval will be short. It is one of the option we can take for difficult situation.

**Comment by ISDL29** [comment]
Thanks for the fast reply. I have deleted my account and requested a new one. Once I can use Studio Lab again, I will try to work with tensorflow and post in this thread the errors I come across.

**Comment by icoxfog417** [comment]
I’m very glad to hear about your Studio Lab environment back! To separate the environment from the default `studiolab` environment is useful to isolate the development environment. Here is the sample of the command (`your-ml-env` is arbitrarily name). 

```
conda create -n your-ml-env tensorflow
```

The created environment can be removed.

```
conda env remove -n your-ml-env
```

Please check the [`conda` command reference](https://docs.conda.io/projects/conda/en/latest/commands.html) for further information.

**Comment by icoxfog417** [comment]
@ISDL29 , did the above solution work? Please let me know if you still have the trouble.

**Comment by ISDL29** [comment]
Yes! Finally I have been able to finish my project thanks to Studio Lab and your support. Thank you very much!! 😄
