### ISSUE TITLE
Amazon sagemaker studio lab account not yet  activated its been 15 days

### ISSUE THREAD

**Issue by Satya-codewalababa** [aws/studio-lab-examples#139]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by icoxfog417** [comment]
Dear @Satya-codewalababa , thank you for trying to use Studio Lab. We are dealing with each request in order. 15 days were longer than our ordinal process. Please inform us of your information from the following form.

https://pages.awscloud.com/GLOBAL_PM_PA_amazon-sagemaker_20211116_7014z000000rjq2-registration.html

**Comment by Satya-codewalababa** [comment]
Hi yesterday i got the account access fortunately, Thank you for the response

**Comment by icoxfog417** [comment]
It sounds great! Thank you for your patience to start to use Studio Lab. If you have the trouble or any feature request to Studio Lab, please let us know.
