### ISSUE TITLE
 ImportError: libgthread-2.0.so.0: cannot open shared object file: No such file or directory while import cv2

### ISSUE THREAD

**Issue by geyee** [aws/studio-lab-examples#14]
**Describe the bug**

After I have runned `%conda install opencv-python` or `%pip install opencv-python command` on SageMaker StudioLab notebooks by selecting the default  Python kernel , `import cv2` not work 。

**To Reproduce**

```
import cv2

---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
/tmp/ipykernel_50/571303353.py in <module>
----> 1 import cv2


~/.conda/envs/default/lib/python3.9/site-packages/cv2/__init__.py in <module>
      3 import sys
      4 
----> 5 from .cv2 import *
      6 from .data import *
      7 

ImportError: libgthread-2.0.so.0: cannot open shared object file: No such file or directory
```
**Expected behavior**
If one has the root premission, `sudo apt-get install libglib2.0-dev` may solve the problem.
using ctypes、importlib and  libglib-2.0.so.0、libgthread-2.0.so.0 files may solve it   too(#https://github.com/Azure/azure-functions-python-worker/issues/497#issuecomment-540830721 )， but the behave is not elegant.
**Screenshots**
![image](https://user-images.githubusercontent.com/20720815/145353693-418f33b0-f735-4343-904d-691ddd2cc8ad.png)

**Desktop (please complete the following information):**
 - OS:  Linux default 4.14.252-195.483.amzn2.x86_64   <i>#</i>1 SMP Mon Nov 1 20:58:46 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

 - Python: 3.9.7
 - conda: 4.10.3

**Additional context**
one question like this #https://github.com/aws/sagemaker-python-sdk/issues/1546#issuecomment-663145510

**Comment by EmilyWebber** [comment]
For this issue, please just add "headless." So the full install is `%pip install opencv-python-headless.` 

Details are here: https://programmerah.com/installing-opencv-python-in-docker-container-15489/ 

Worked for me! Thanks.

**Comment by geyee** [comment]
> For this issue, please just add "headless." So the full install is `%pip install opencv-python-headless.`
> 
> Details are here: https://programmerah.com/installing-opencv-python-in-docker-container-15489/
> 
> Worked for me! Thanks.

I am not very familiar with opencv and the  selection of search terms are incomplete, so I didn't find the answer directly before. As mentioned in the above link, [docker环境里安装opencv ImportError: libGL.so.1: cannot open shared object file: No such file or directory](https://blog.csdn.net/Max_ZhangJF/article/details/108920050) and  #https://github.com/Korea-Health-Datathon/KHD2020/issues/78#issuecomment-696583219 describes the solution: you just need to install the headless opencv python package ,ie opencv-python-headless. https://github.com/Azure/azure-functions-python-worker/issues/497#issuecomment-549253561 also mentioned the solution that I ignored. Thank you.

PS，some other links may be useful, too [在docker容器中安装opencv-python](https://blog.csdn.net/see_you_yu/article/details/112908221)，[Docker容器内安装opencv-python](https://blog.csdn.net/dwqy11/article/details/112585754)，[opencv ImportError: libGL.so.1: cannot open shared object file: No such file or directory](https://blog.csdn.net/guotianqing/article/details/115253263)，[ImportError: libGL.so.1: cannot open shared object file: No such file or directory cv2报错](https://blog.csdn.net/qq_38284961/article/details/109361158),
[続 Azure Functions の python 関数で OpenCV を使う](https://uncaughtexception.hatenablog.com/entry/2019/10/06/101007),
https://github.com/keithrozario/Klayers/issues/115,
[Missing .SO files in Lambda functions](https://www.keithrozario.com/2021/08/missing-so-files-in-lambda-functions.html),
https://github.com/opencv/opencv-python/issues/208 。

**Comment by ElNoSabe322** [comment]
I'm having this same issue but I'm trying to install YOLO from ultralytics. 
%pip install ultralytics works fine but when I try to do ```from ultralytics import YOLO```, I keep running into this error. 
And the "headless" flag does not seem to work here. 

Does anyone have a solution?

**Comment by banhmysuawx** [comment]
same to me
