### ISSUE TITLE
My account was not accepted

### ISSUE THREAD

**Issue by bobbie7wei1998** [aws/studio-lab-examples#140]
I applied for registration on 7/31/2022

My request has not yet been accepted ؟

**Comment by icoxfog417** [comment]
Dear @bobbie7wei1998, thank you for letting us know your situation. The approval took over 2 weeks, and it is longer than our ordinal process. Please inform us of your information from the following form.

https://pages.awscloud.com/GLOBAL_PM_PA_amazon-sagemaker_20211116_7014z000000rjq2-registration.html

**Comment by icoxfog417** [comment]
Dear @bobbie7wei1998 , if your account is not approved yet, please let us know again. I close this issue.
