### ISSUE TITLE
Can't start a session for two days:

### ISSUE THREAD

**Issue by gladex** [aws/studio-lab-examples#142]
**Describe the bug**
Studio Lab can not start the CPU mode for several days. It responds "There was a problem when loading your project. ...."

**Expected behavior**
Studio Lab can not start even in the CPU mode.

**Screenshots**
![SMSL_Bug](https://user-images.githubusercontent.com/7739145/186298912-2f61e311-2177-4fe7-b9c0-a27edce4a646.jpg)

**Desktop:**
 - OS: Windows 11
 - Browser: MS Edge

**Comment by gladex** [comment]
> Dear @gladex, sorry for the inconvenience of the instance. Now I confirmed to launch the CPU instance without error, how about you? We can not launch the GPU instance now and we have already started the action to solve this. We will notify you when the problem solved.

Hi Sir,

I still can not open the instance with any CPU or GPU mode. The page keeps showing preparing project runtime. I tried opening both Chrome and Edge, but it failed all the time.

![11](https://user-images.githubusercontent.com/7739145/187711566-a57f777f-d627-4ed3-9425-8d1ccd69d493.jpg)

Please find time to help check it. Many thanks in advance.

**Comment by icoxfog417** [comment]
Thank you for reporting us the problem. It is serious. Could you please try the delete / recreate the account if you can? I have had the same situation and the recreate account solved the problem.

https://github.com/aws/studio-lab-examples/issues/138

We are very glad if you share the process until you faced this problem. For example, what kind of command did you do or what  operation did you do. It is useful information to make the preventive measure.

**Comment by gladex** [comment]
Hi Sir,
It works after deleting and recreating the account. I think this is due to that previously I unintentionally deleted one environment "default".
===
default                  /home/studio-lab-user/.conda/envs/default
studiolab             *  /home/studio-lab-user/.conda/envs/studiolab
base                     /opt/conda
===

 Thanks a lot for your help.

**Comment by icoxfog417** [comment]
That's good news! Thank you for sharing the your situation. I have not deleted the `default` and it is insightful report that to delete  the `default` causes the issue. If could you solve the problem, please let us know by closing the issue.

**Comment by gladex** [comment]
@icoxfog417 
That's good. Thanks a lot for your work.

**Comment by icoxfog417** [comment]
@gladex Your welcome. We are very glad if we can contribute your learning. Please let us know if you publish the blog post that uses Studio Lab!
