### ISSUE TITLE
Can't download file

### ISSUE THREAD

**Issue by fmafelipe** [aws/studio-lab-examples#143]
I can't download a trained model that weighs around 630 MB, the download never starts

**Comment by icoxfog417** [comment]
Dear @fmafelipe, thank you for using the Studio Lab. And sorry for the inconvenience. Can not download the trained model would be stressful. Can you download the other files that lighter size than model? I want to know this phenomenon is depend on the file size or not.

As a temporary solution, we can save the model in the S3 through the awscli and download file from the AWS Management Console. Of course, the other cloud or Google Drive is alternative.

**Comment by fmafelipe** [comment]
@icoxfog417,
yes, in fact other lighter files if I can download them, I will try with the recommendations, thanks.

**Comment by icoxfog417** [comment]
Thank you for your effort. [`aws s3 cp`](https://awscli.amazonaws.com/v2/documentation/api/latest/reference/s3/index.html) is the simple command to upload file to S3. After you [setting up configuration](https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-quickstart.html), you can execute this command. Please let us know if you solve the problem.

**Comment by icoxfog417** [comment]
We merge this issue to https://github.com/aws/studio-lab-examples/issues/190 .
