### ISSUE TITLE
Account not approved after 2 weeks

### ISSUE THREAD

**Issue by RandallB12** [aws/studio-lab-examples#146]
I have not been approved to create an account and the FAQ says "Account requests are typically approved within 1 to 5 business days." but it has been **2 weeks**  and as forementioned, my account has not been approved. 
I have also filled the form as previously outlined in some posts by users who were also having the same issue but to no avail as it has also been a week since I filled the form but there was no response.

Please help me out.

**Comment by MicheleMonclova** [comment]
yes, we are running a bit behind on approvals. Expect to see it come through in next couple of days.

**Comment by icoxfog417** [comment]
@RandallB12 is your account still not approved? We are glad if you tell us the status.

**Comment by icoxfog417** [comment]
I will close this issue. Please feel free to raise a new issue if you still have the trouble.
