### ISSUE TITLE
After login, I can't access the project, due to a script error

### ISSUE THREAD

**Issue by sabino4875** [aws/studio-lab-examples#147]
**After login, I can't access the project, due to a script error**

**To Reproduce**
When clicking on the button to start the project, it takes about five seconds and returns a message informing that there is no environment available, to try again later.
After checking the page for errors, an error was identified when loading the script, as shown in the attached image.

**Screenshots**
![bloqueio_acesso_aws_sagemaker_studio_2022_10_23_06_52_47](https://user-images.githubusercontent.com/115749791/197385832-c026f4c7-2559-4cda-8f5d-c0feadd9cad3.png)

**Desktop (please complete the following information):**
 - OS: Xubuntu
 - Browser: Chrome
 - Version: 22.0.4

**Comment by MicheleMonclova** [comment]
Hi, it is against our use policy to use scripts to get access. This creates an unfair distribution of compute to our community. Customers using scripts to get instances may be blocked from the service. Please instead use the Start Runtime button.

**Comment by MicheleMonclova** [comment]
Sorry - this was not a scripting issue, but we simply had low CPU that day. We recently increased our capacity.

**Comment by MicheleMonclova** [comment]
Is this still an open issue?

**Comment by icoxfog417** [comment]
I will close this issue. Please feel free to raise a new issue if you still have the trouble.
