### ISSUE TITLE
Error when creating account

### ISSUE THREAD

**Issue by Jordan231111** [aws/studio-lab-examples#149]
I was approved several hours ago however, I have tried multiple password combinations and username combinations but I am unable to create account.
Your email, password, or username is not allowed. Please check the requirements and try again.

**Comment by icoxfog417** [comment]
Hi @Jordan231111 , are you trying to create the account from the approval email link ? There is a expiration date until creating the account. Please check the date and if it is expired, please request account again. If you are already approved, you can get the approval email soon.

**Comment by Jordan231111** [comment]
Hi, I forgot to follow up but despite getting errors I still ended up receiving the email to activate my account. Thank you
