### ISSUE TITLE
Add localization example to custom-environments

### ISSUE THREAD

**Issue by icoxfog417** [aws/studio-lab-examples#152]
**Is your feature request related to a problem? Please describe.**
As developers for non native English need the tutorial to localize the Studio Lab interface.

**Describe the solution you'd like**
We can localize the interface by using [jupyterlab -language-pack](https://anaconda.org/search?q=jupyterlab-language-pack).
We will introduce how to install and setup the language pack.

**Describe alternatives you've considered**
None

**Additional context**
I will create the pull request for this issue.

**Comment by MicheleMonclova** [comment]
Great suggestion!

**Comment by icoxfog417** [comment]
I added the example.
