### ISSUE TITLE
Problem with making new account

### ISSUE THREAD

**Issue by jessa2003** [aws/studio-lab-examples#154]
**Describe the bug**
I received the OK to my new account by email.

**To Reproduce**
1. I Followed the link that I received
2. I Completed all the requested fields
3. Submit the form

**Expected behavior**
Granted the account.

**Screenshots**
![image](https://user-images.githubusercontent.com/57605061/199572930-8c6c210d-17e2-426c-afc2-a0fafbb1a692.png)

**Desktop (please complete the following information):**
 - OS: windows 10
 - Browser Chrome

**Additional context**

**Comment by icoxfog417** [comment]
@jessa2003 Thank you for creating the account. To make your account, could you please request account again? If your approval has expired as the error message show, you can receive the approval by sending the request account again. When your account is already approved, you can get approval mail soon.

**Comment by jessa2003** [comment]
That happened last week (my approval expired) so I sent it again yesterday and today I received the email confirmation. But if you understand that I have to repeat my request OK.
Enviado desde Yahoo Mail para Android 
 
  El mié, 2 de nov. de 2022 a la(s) 22:03, Takahiro ***@***.***> escribió:   


@jessa2003 Thank you for creating the account. To make your account, could you please request account again? If your approval has expired as the error message show, you can receive the approval by sending the request account again. When your account is already approved, you can get approval mail soon.

**Comment by icoxfog417** [comment]
Thank you for sending you request again. After you receive the account approval mail, you can create your account.

**Comment by MicheleMonclova** [comment]
Let me know your status.  I suspect you might have a capitalization problem.  Right now user email is case sensitive.

**Comment by jessa2003** [comment]
You were right! I requested my account again and all was granted OK.
Thanks!Saludos, Jessica 

    On Friday, November 4, 2022, 02:29:23 PM GMT-3, MicheleMonclova ***@***.***> wrote:  
 
 


Let me know your status. I suspect you might have a capitalization problem. Right now user email is case sensitive.

**Comment by icoxfog417** [comment]
Your welcome. I hope you enjoy your machine learning journey in Studio Lab!
