### ISSUE TITLE
Phone number verification for GPU use fails when number is less than 12 digits long

### ISSUE THREAD

**Issue by GitchNZ** [aws/studio-lab-examples#159]
**Description**
When attempting to start a GPU runtime, you are prompted for a phone number in international format. However, if you happen to have a phone number that is less than 12-digits, you are unable to register it. Instead, you receive an error "please enter an-12 digit phone number".

**To Reproduce**
1. Change the runtime to GPU
2. Click on 'start runtime'
3. Accept any prompts
4. Enter your phone number in the correct international format.
5. If your number happens to be less than 12 digits long, You will receive an error and signup will not complete. 

**Expected behavior**
The interface should allow all legitimate phone numbers to be added, rather than only those that happen to be 12 digits or more long. Given that the number is used for verification, this in itself should serve as the test of whether a number is legitimate or not. Length of a phone number is not a guaranteed way to determine this, and potentially prevents entire countries from ever verifying their number. 

**Desktop (please complete the following information):**
 - OS: Windows and IOS
 - Browser Firefix, Chrome, Safari

**Comment by MicheleMonclova** [comment]
We are looking in to this. Until then please use CPU.

**Comment by ddathaguycloudacio** [comment]
Also have this problem for Uruguay, which is requesting 17 digits while should be less.

**Comment by SteaGea** [comment]
Also have this problem for Malta. The phone number should be 8 digits in length (excluding the +356 dialing code). Error message as follows: "Enter an17-digit phone number."

**Comment by MicheleMonclova** [comment]
Hi all, we just rolled out a fix - please retry.

**Comment by SteveGalea** [comment]
Thank you!

**Comment by MicheleMonclova** [comment]
if you are up and running can you please close this issue? thanks!

**Comment by icoxfog417** [comment]
We close this issue. The implementation is based on [E.164 format](https://www.itu.int/rec/T-REC-E.164/en) and that it is not a VoIP or landline number. If the phone number meets those requirements but you still get the error, wait a few minutes and try again.

For more detail, please refer the [FAQ: Why did I get an error when I entered my phone number? section](https://studiolab.sagemaker.aws/faq)

**Comment by SaraIrfa** [comment]
Hi, I am also getting this error. Please share your suggestions so that I can fix it.

**Comment by MicheleMonclova** [comment]
the multi digit issue mentioned in this thread was fixed. However you may be running into a different problem which is your phone carrier may not have your phone categorized as 'Mobile', some have it categorized as 'Other'. 
This is a know problem. Do you have a different mobile number you can use?
