### ISSUE TITLE
Error Starting Kernel: No space left on device

### ISSUE THREAD

**Issue by polodealvarado** [aws/studio-lab-examples#16]
**Describe the bug**
Starting the Kernel, the browser shows:

Error Starting Kernel
[Errno 28] No space left on device: '/home/studio-lab-user/.local/share/jupyter/runtime/kernel-b45de32e-b211-4e8e-b7b0-ccc1914268af.json'

**Expected behavior**
Work without problems

**Additional context**
Is it possible to release memory ?

**Comment by EmilyWebber** [comment]
Hi - given the 15GB limits of Studio Lab you'll want to be careful about what you are storing. Generally it's a good practice to delete files you don't need. If you are looking for a full factory reset, ie to delete literally all of the files and packages, you can use `rm -rf .*`. Tread with caution, as this will clear all of your data. 

https://docs.aws.amazon.com/sagemaker/latest/dg/studio-lab-use-manage.html

**Comment by polodealvarado** [comment]
Thanks ! @EmilyWebber

**Comment by robmarkcole** [comment]
I would caution that doing so results in 

```EnvironmentLocationNotFound: Not a conda environment: /home/studio-lab-user/.conda/envs/studiolab```
