### ISSUE TITLE
Studio Lab no longer connects to the d2l:Python kernel

### ISSUE THREAD

**Issue by dcbarnard** [aws/studio-lab-examples#168]
Is there a simple way to restore my SageMaker Studio Lab environment so that it connects successfully again to the d2l:Python kernel? Previously, I could connect to either the Python kernel or the d2l:Python kernel, but starting yesterday I can only connect to the Python kernel. I may have created this problem by installing packages required for a task.

**Comment by icoxfog417** [comment]
How did you create your `d2l:Python` kernel? Basically, created environment is saved in the persistent storage so that you can access to it after you stop the runtime.

**Comment by dcbarnard** [comment]
I created it following the instructions in the GettingStarted-D2L.ipynb notebook preview. I suppose my simplest approach would be to use conda remove --name d2l --all, and then recreate the environment following the same instructions?

**Comment by icoxfog417** [comment]
The `conda remove` and recreate it is the right instruction to restore your `d2l` environment. It is effective when you need the original `d2l` environment. We can create the conda environment by right click the `environment.yml` and select "Build Conda Environment" in the Studio Lab.

![image](https://user-images.githubusercontent.com/544269/204168303-db395efd-7701-4ec3-895f-71998042cb9b.png)

**Comment by icoxfog417** [comment]
I close this issue. Please contact us if you still have the problem.
