### ISSUE TITLE
Add RAPIDS custom environment

### ISSUE THREAD

**Issue by icoxfog417** [aws/studio-lab-examples#170]
**Describe the use case example you want to see**
A link to [RAPIDS + SageMaker Studio Lab Quick Start Repo](https://github.com/rapidsai-community/rapids-smsl) to introduce how to set up RAPIDS in SageMaker Studio Lab. The link will be added at [custom environments section](https://github.com/aws/studio-lab-examples#custom-environments).

**How would this example be used? Please describe.**
Onboarding new customers who need GPU accelerated data science and analytics to Studio Lab.

**Describe which dataset could be used. Provide its location in s3://sagemaker-sample-files or another source.**
None

**Describe which SageMaker services are involved**
None

**Describe what other services (other than SageMaker) are involved***
None

**Comment by taureandyernv** [comment]
Happy to help with this issue.  What are the needs/process?  Also, RAPIDS is testing out a pip install option, which takes up a little less room on the instance, is a bit faster than the current conda install capability.

**Comment by icoxfog417** [comment]
We added the link to RAPIDS example to README.md.
