### ISSUE TITLE
Requires Phone Number. Nowhere to Enter Phone Number.

### ISSUE THREAD

**Issue by omicreativedev** [aws/studio-lab-examples#171]
**Describe the bug**
Dashboard says, "SageMaker Studio Lab now requires users to provide their phone number for compute. See FAQ for details."
But there is nowhere in the account or dashboard to enter a phone number.

**To Reproduce**
1. Go to Dashboard
2. Click on (nothing, that's the point)

**Expected behavior**
Place to enter phone number in account dashboard.

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro
 - Browser Chrome
 - Version latest

**Comment by icoxfog417** [comment]
Thank you for trying the Studio Lab. Did you click the "start runtime"? We can enter the phone number when launching the CPU / GPU instance.

**Comment by icoxfog417** [comment]
I close this issue. Please contact us if you still have the problem.

**Comment by icoxfog417** [comment]
@longhowlam, thank you for reporting the issue. This is the closed issue so that please create a new issue for you.
