### ISSUE TITLE
Add Stable Diffusion Diffuser environment to custom-environments

### ISSUE THREAD

**Issue by maekawataiki** [aws/studio-lab-examples#172]
**Is your feature request related to a problem? Please describe.**
It would be nice SageMaker Studio Lab has example to setup Stable Diffusion.

**Describe the solution you'd like**
Prepare the environment.yml for `diffusers`. The dependencies should include packages to run Stable Diffusion.

**Describe alternatives you've considered**
Install the `diffusers` and the other dependencies by conda command.

**Additional context**

**Comment by icoxfog417** [comment]
Thanks to @maekawataiki , we added `diffusers` environment!
