### ISSUE TITLE
unable to use librosa (package for music/audio analysis)

### ISSUE THREAD

**Issue by mrleu** [aws/studio-lab-examples#18]
**Describe the bug**
studio lab allows for conda install `librosa`, however librosa still needs `sndfile` to function. seems like online tutorial have been suggesting to use apt-get install to make it happen, but i am unable to use apt-get to install this function(not a root.)

Curious to know if there are suggestion to make it work?

**To Reproduce**
1. run `pip install librosa`
2. on notebook, do `import librosa`

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**

**Comment by mrleu** [comment]
solved

**Comment by mizoru** [comment]
How did you solve this issue?

**Comment by mrleu** [comment]
instead of using apt-get to install `snd-file` , i used conda to install soundfile with
```
conda install pysoundfile -c conda-forge
```
