### ISSUE TITLE
This phone number is invalid.

### ISSUE THREAD

**Issue by fullstackwebdev** [aws/studio-lab-examples#180]
Unable to use my phone number user dmx1

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**
![Screenshot from 2022-12-10 13-28-21](https://user-images.githubusercontent.com/10137946/206875924-957f142a-7599-4df7-857c-2f7e76b390df.png)

**Comment by MicheleMonclova** [comment]
what is dmx1?

**Comment by fullstackwebdev** [comment]
Username dmx1

**Comment by MicheleMonclova** [comment]
Ok thanks.

There may be several causes to this error: Make sure the number is in an [E.164 format](https://www.itu.int/rec/T-REC-E.164/en), and that it is not a VoIP or landline number. If the phone number meets those requirements but you still get the error, then go to this form and tell us what phone number you are using.  This form will keep your information private so you don't need to put in this open forum.

**Comment by fullstackwebdev** [comment]
Sorry, which form to I go to?

**Comment by MicheleMonclova** [comment]
https://pages.awscloud.com/GLOBAL_PM_PA_amazon-sagemaker_20211116_7014z000000rjq2-registration.html

**Comment by icoxfog417** [comment]
We close this issue. We mentioned about phone number format in FAQ.

https://studiolab.sagemaker.aws/faq
