### ISSUE TITLE
couldnt install any library at all

### ISSUE THREAD

**Issue by aozorahime** [aws/studio-lab-examples#183]
**Describe the bug**
No idea about the current version of sagelab since I didn't touch it for almost a month. Today I created a new env by conda and wanted to install some libraries and dependencies. The installation said it is successful however when I wanna run something, it says no module name TensorFlow and other things. I checked with conda list, all none. I tried adding --user command but it doesn't work.

Here is the error :

`ERROR: Could not install packages due to an OSError: [Errno 13] Permission denied: '/opt/conda/lib/python3.9/site-packages/zipp'
Consider using the `--user` option or check the permissions.`

Please, any idea about this?

**Comment by icoxfog417** [comment]
To identify the cause, we need more information. Could you let us know about your goal and what did you to reach it? 
I assume that your goal is to use TensorFlow. The following command create the `tensorflow` environment that can be used as Kernel.

```
conda create -n tensorflow tensorflow ipython ipykernel
```

**Comment by icoxfog417** [comment]
We cloes this issue. Please use above command to build the tensorflow environment.
