### ISSUE TITLE
Connection to kernel fails

### ISSUE THREAD

**Issue by raghavchandra123** [aws/studio-lab-examples#185]
**Describe the bug**
Though working just yesterday, now when trying to run my jupyter notebook, the kernel doesn't connect and the menu only shows default kernel even though I have multiple environments set up and "conda env list" lists all of the environments properly. I have tried restarting everything (jupyter, cpu instance and file) but problem persists

**To Reproduce**
Try to run Jupyter notebook

**Expected behavior**
Should connect to kernel and run

**Screenshots**
![image](https://user-images.githubusercontent.com/87539037/210087872-59abe768-4c74-43af-a513-c4962e471fad.png)
![image](https://user-images.githubusercontent.com/87539037/210087919-f51543c0-955f-463a-a4be-727fd87f7b1f.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Chrome
 - Version 108

**Additional context**

**Comment by icoxfog417** [comment]
Have you ever connected to the your created conda environment from Jupyter Lab in Studio Lab? When we created conda environment, we should run `ipython kernel install` to use these as a kernel. It is the default behavior in Jupyter Lab.

**Comment by raghavchandra123** [comment]
As an update, now I cannot access my files in what seems to be a fatal error and it gives error message: "There was a problem when loading your project. This should be resolved shortly. Please try again later." It would be great if I could somehow download the data or reset the environments if that is what is causing a problem.

**Comment by icoxfog417** [comment]
As you have already read about the issue, to recreate the account is the solution when we can not launch the project. Unfortunately, the data is cleared when recreating the account.

https://github.com/aws/studio-lab-examples/issues/138

If you remember what operation caused this error, please let us know to fix the problem that bothering you.

**Comment by raghavchandra123** [comment]
Yes i have seen this thanks, i am not sure this is a good solution as it results in complete data loss, the operation that caused the error is almost certainly to do with environments and allowing reset to default environment would fix the problem i assume. To me it seems that this is not a well maintained service by amazon, it seems strange that a fatal error reported several times can remain unfixed for so many months with no decent solution or data recovery methods. I will switch over to azure student

**Comment by icoxfog417** [comment]
Sorry for the inconvenience. If you push the working result to the Git repository, you can clone / pull the contents from it. 
We hope you try Studio Lab again after our continuous update.

**Comment by raghavchandra123** [comment]
Yes but i cant push the result to github without access to the files

**Comment by MicheleMonclova** [comment]
raghavchandra123, thanks for raising this to our attention. We will see if we can recreate it so it can be fixed.
