### ISSUE TITLE
Allow S3 to be mounted in Studio Lab

### ISSUE THREAD

**Issue by fkunn1326** [aws/studio-lab-examples#186]
**Is your feature request related to a problem? Please describe.**
I would like to be able to mount external storage such as S3 to Studio lab, as the current 15GB storage is sometimes not enough.

**Describe the solution you'd like**
Allow s3fs to be installed in the studio lab.

**Describe alternatives you've considered**
- Deleting and redownloading the data needed.

I am sorry if it is rude or inappropriate to you, since I use the online translation site.

**Comment by fkunn1326** [comment]
Also, it seems that studio lab is running on docker, so you need to enable fuse to mount it

**Comment by icoxfog417** [comment]
Dear @fkunn1326 , thank you for your great idea. We will discuss at the following issue.

https://github.com/aws/studio-lab-examples/issues/178
