### ISSUE TITLE
I want to download a package but it only use apt command,when I use apt-get, it reminds me I don't have enough permissions,do you have any ways to solve it？Please tell me, thanks

### ISSUE THREAD

**Issue by YanjunTong** [aws/studio-lab-examples#195]
My problem is shown in the photo. "How to use apt commands on the sagemaker studio lab?"
![mmexport1674753738949](https://user-images.githubusercontent.com/114793575/214905805-7e2e0129-d57f-43e7-abf5-3a53bbcc22e7.png)
I want to download the package libgthread-2.0.so.0,but it only use apt commands,when I use conda or pip,it reminds me can't find. If I use apt-get libgthread-2.0.so.0 it will reminds me I don't have enough permissions.So what should I do now? If someone has ways to solve it,please tell me.I'm not good at English expression,please understand.Thanks a lot.
You can reply me here or use my mailbox at yanjun_tong@outlook.com

**Comment by icoxfog417** [comment]
Hi @YanjunTong , we do not allow the `apt install` in Studio Lab. I assume that if you would like to use OpenCV (because `libglib2.0-0` is used in OpenCV), you can install it by `conda install -c conda-forge opencv`.

**Comment by YanjunTong** [comment]
Thank you very much, I will try it.

获取Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
