### ISSUE TITLE
The Sagemaker Studion lab uploads files too low

### ISSUE THREAD

**Issue by YanjunTong** [aws/studio-lab-examples#196]
The Sagemaker Studio Lab uploads files' speed is too low. Last time I uploaded a file, The file size was about 2GB,but I spent more than two hours to completed it.Does anyone have any ways to solves it？

**Comment by icoxfog417** [comment]
@YanjunTong Thank you for using Studio Lab. We would like to separate the problem. Can you upload your file quickly when you upload to the DropBox, Google Drive or the other storage service? This question is to separate the network speed problem and the Studio Lab upload process delay problem. If you are  already using Amazon S3, uploading to S3 / and downloading from here is one of the alternative ways to deal with the large file.
