### ISSUE TITLE
Open project load infinitely.

### ISSUE THREAD

**Issue by BrinthanK** [aws/studio-lab-examples#197]
When I click the open project, the tab loads infinitely. Is there any solution to at least recover the data inside?

**Comment by MicheleMonclova** [comment]
That doesn’t sound good. Can you give some more info? Gpu? CPU? Do you know how much storage ? We can try to reproduce what happened.

**Comment by BrinthanK** [comment]
@MicheleMonclova  I got back my account. Seems that is an error in their server. Thanks for considering this.
