### ISSUE TITLE
Unable to access my account and result files due to violation complaint.

### ISSUE THREAD

**Issue by hollarme** [aws/studio-lab-examples#199]
Hello all,

Please, my account on sage maker was disabled or deleted for violation. Unfortunately, I do not know how I violated the service conditions in any way. 

Can I at least download all the results I have gotten so far from the sage maker even if I will not be allowed to use the tool again. I tried requesting for another account but all to no avail. 

Those results are needed for my program. Please help!!!

**Comment by npmajisha-github** [comment]
Hello,

Please provide your details in this form - https://pages.awscloud.com/GLOBAL_PM_PA_amazon-sagemaker_20211116_7014z000000rjq2-registration.html and we can take a look.

Note your account will be deleted within 7 days of the first email citing violation of terms and conditions. We will not be able to recover your data beyond the 7 days.

**Comment by hollarme** [comment]
Thank you!
