### ISSUE TITLE
"There is no runtime available right now"

### ISSUE THREAD

**Issue by NelsonMoore00** [aws/studio-lab-examples#203]
I'm getting this error for the CPU runtime so my work is currently stuck. Can you please fix this issue? This is also the issue for GPU but I mostly utilize the CPU notebook.

**Comment by icoxfog417** [comment]
Sorry for the inconvenience, please refer the replies in the following issue. We are tackling this issue eagerly from the last year.

https://github.com/aws/studio-lab-examples/issues/202

**Comment by MicheleMonclova** [comment]
Hi NelsonMoore00, is this still an issue or can we close it.

**Comment by icoxfog417** [comment]
We close this issue and merge to #202.
