### ISSUE TITLE
Something went wrong. Please try again later

### ISSUE THREAD

**Issue by aozorahime** [aws/studio-lab-examples#205]
**Describe the bug**
I am not quite sure, does the CPU is not available? It's been 3 days, I couldn't access the service, moreover, most of my current experiment notebooks are there. I need to use it to continue the ongoing code.

**Screenshots**
![image](https://user-images.githubusercontent.com/38600745/225219815-ef287075-d84a-4dd5-bbe9-ecb70b3df2af.png)

Desktop (please complete the following information):

OS: Windows
Browser Chrome

**Comment by mymywang** [comment]
Hi @aozorahime, apologize for the issue you encountered. It should be resolved now. Could you try again and verify? Thank you for using SageMaker Studio Lab.

**Comment by aozorahime** [comment]
@mymywang it works now, thanks!
