### ISSUE TITLE
jupytext support

### ISSUE THREAD

**Issue by hhoppe** [aws/studio-lab-examples#208]
`jupytext` is a nice extension to synchronize a `ipynb` notebook with a text-only `py` file --- this provides nice revision history.

Trying to enable the `jupyterlab-jupytext` extension gives the message:

> This package has indicated that it needs a corresponding server extension. Please contact your Administrator to update the server with one of the following commands:
> pip install jupytext
> conda install -c conda-forge jupytext
> You should make sure that the indicated packages are installed before trying to use the extension. Do you want to continue with the extension installation?

Would it be possible to support this in the server?

**Comment by hhoppe** [comment]
Never mind, I was able to get this working, by using
```
!conda install jupytext
```
and then re-starting the runtime.

**Comment by MicheleMonclova** [comment]
Thanks Hhoppe! I've never used that extension before.  Maybe we add to our documentation.
