### ISSUE TITLE
it is requested to update conda from version 4 to version 23 but updating fails

### ISSUE THREAD

**Issue by Sandy4321** [aws/studio-lab-examples#210]
**Describe the bug**
I use 
https://github.com/aws/studio-lab-examples
![image](https://user-images.githubusercontent.com/11426119/232335790-b5037995-5b08-40e6-80ca-fc55e38947bd.png)

it is requested to update conda from version 4 to version 23
but updating fails

(studiolab) studio-lab-user@default:~/sagemaker-studiolab-notebooks$ conda update -n base conda
Collecting package metadata (current_repodata.json): done
Solving environment: done

## Package Plan ##

  environment location: /opt/conda

  added / updated specs:
    - conda

The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    boltons-23.0.0             |     pyhd8ed1ab_0         296 KB  conda-forge
    brotlipy-0.7.0             |py39hb9d737c_1005         342 KB  conda-forge
    certifi-2022.12.7          |     pyhd8ed1ab_0         147 KB  conda-forge
    cffi-1.15.1                |   py39he91dace_3         229 KB  conda-forge
    charset-normalizer-3.1.0   |     pyhd8ed1ab_0          44 KB  conda-forge
    colorama-0.4.6             |     pyhd8ed1ab_0          25 KB  conda-forge
    conda-23.3.1               |   py39hf3d152e_0         933 KB  conda-forge
    conda-package-handling-2.0.2|     pyh38be061_0         247 KB  conda-forge
    conda-package-streaming-0.7.0|     pyhd8ed1ab_1          17 KB  conda-forge
    cryptography-40.0.2        |   py39h079d5ae_0         1.4 MB  conda-forge
    idna-3.4                   |     pyhd8ed1ab_0          55 KB  conda-forge
    jsonpatch-1.32             |     pyhd8ed1ab_0          14 KB  conda-forge
    jsonpointer-2.0            |             py_0           9 KB  conda-forge
    pluggy-1.0.0               |     pyhd8ed1ab_5          16 KB  conda-forge
    pycosat-0.6.4              |   py39hb9d737c_1         108 KB  conda-forge
    pycparser-2.21             |     pyhd8ed1ab_0         100 KB  conda-forge
    pyopenssl-23.1.1           |     pyhd8ed1ab_0         125 KB  conda-forge
    pysocks-1.7.1              |     pyha2e5f31_6          19 KB  conda-forge
    requests-2.28.2            |     pyhd8ed1ab_1          56 KB  conda-forge
    ruamel.yaml-0.17.21        |   py39h72bdee0_3         184 KB  conda-forge
    ruamel.yaml.clib-0.2.7     |   py39h72bdee0_1         140 KB  conda-forge
    toolz-0.12.0               |     pyhd8ed1ab_0          48 KB  conda-forge
    tqdm-4.65.0                |     pyhd8ed1ab_1          86 KB  conda-forge
    urllib3-1.26.15            |     pyhd8ed1ab_0         110 KB  conda-forge
    zstandard-0.19.0           |   py39h29414ee_1         373 KB  conda-forge
    zstd-1.5.2                 |       h3eb15da_6         410 KB  conda-forge
    ------------------------------------------------------------
                                           Total:         5.5 MB

The following NEW packages will be INSTALLED:

  boltons            conda-forge/noarch::boltons-23.0.0-pyhd8ed1ab_0
  bzip2              conda-forge/linux-64::bzip2-1.0.8-h7f98852_4
  conda-package-str~ conda-forge/noarch::conda-package-streaming-0.7.0-pyhd8ed1ab_1
  jsonpatch          conda-forge/noarch::jsonpatch-1.32-pyhd8ed1ab_0
  jsonpointer        conda-forge/noarch::jsonpointer-2.0-py_0
  libnsl             conda-forge/linux-64::libnsl-2.0.0-h7f98852_0
  libsqlite          conda-forge/linux-64::libsqlite-3.40.0-h753d276_0
  libuuid            conda-forge/linux-64::libuuid-2.38.1-h0b41bf4_0
  libzlib            conda-forge/linux-64::libzlib-1.2.13-h166bdaf_4
  packaging          conda-forge/noarch::packaging-23.1-pyhd8ed1ab_0
  pluggy             conda-forge/noarch::pluggy-1.0.0-pyhd8ed1ab_5
  ruamel.yaml        conda-forge/linux-64::ruamel.yaml-0.17.21-py39h72bdee0_3
  ruamel.yaml.clib   conda-forge/linux-64::ruamel.yaml.clib-0.2.7-py39h72bdee0_1
  toolz              conda-forge/noarch::toolz-0.12.0-pyhd8ed1ab_0
  zstandard          conda-forge/linux-64::zstandard-0.19.0-py39h29414ee_1
  zstd               conda-forge/linux-64::zstd-1.5.2-h3eb15da_6

The following packages will be REMOVED:

  chardet-4.0.0-py39hf3d152e_1
  ruamel_yaml-0.15.80-py39h3811e60_1004
  six-1.16.0-pyh6c4a22f_0
  sqlite-3.36.0-h9cd32fc_2
  yaml-0.2.5-h516909a_0
  zlib-1.2.11-h516909a_1010

The following packages will be UPDATED:

  _openmp_mutex                                   4.5-1_gnu --> 4.5-2_gnu
  brotlipy                          0.7.0-py39h3811e60_1001 --> 0.7.0-py39hb9d737c_1005
  ca-certificates                      2021.5.30-ha878542_0 --> 2022.12.7-ha878542_0
  certifi            conda-forge/linux-64::certifi-2021.5.~ --> conda-forge/noarch::certifi-2022.12.7-pyhd8ed1ab_0
  cffi                                1.14.6-py39h4bc2ebd_1 --> 1.15.1-py39he91dace_3
  charset-normalizer                     2.0.0-pyhd8ed1ab_0 --> 3.1.0-pyhd8ed1ab_0
  colorama                               0.4.4-pyh9f0ad1d_0 --> 0.4.6-pyhd8ed1ab_0
  conda                               4.10.3-py39hf3d152e_2 --> 23.3.1-py39hf3d152e_0
  conda-package-han~ conda-forge/linux-64::conda-package-h~ --> conda-forge/noarch::conda-package-handling-2.0.2-pyh38be061_0
  cryptography                         3.4.7-py39hbca0aa6_0 --> 40.0.2-py39h079d5ae_0
  idna                                     3.1-pyhd3deb0d_0 --> 3.4-pyhd8ed1ab_0
  ld_impl_linux-64                        2.36.1-hea4e1c9_2 --> 2.40-h41732ed_0
  libffi                                   3.4.2-h9c3ff4c_4 --> 3.4.2-h7f98852_5
  libgcc-ng                               11.2.0-h1d223b6_9 --> 12.2.0-h65d4601_19
  libgomp                                 11.2.0-h1d223b6_9 --> 12.2.0-h65d4601_19
  libstdcxx-ng                            11.2.0-he4da1e4_9 --> 12.2.0-h46fd767_19
  ncurses                                    6.2-h58526e2_4 --> 6.3-h27087fc_1
  openssl                                 1.1.1l-h7f98852_0 --> 3.1.0-h0b41bf4_0
  pycosat                           0.6.3-py39h3811e60_1006 --> 0.6.4-py39hb9d737c_1
  pycparser                               2.20-pyh9f0ad1d_2 --> 2.21-pyhd8ed1ab_0
  pyopenssl                             20.0.1-pyhd8ed1ab_0 --> 23.1.1-pyhd8ed1ab_0
  pysocks            conda-forge/linux-64::pysocks-1.7.1-p~ --> conda-forge/noarch::pysocks-1.7.1-pyha2e5f31_6
  python                           3.9.7-hb7a2778_2_cpython --> 3.9.16-h2782a2a_0_cpython
  python_abi                                     3.9-2_cp39 --> 3.9-3_cp39
  readline                                   8.1-h46c0cb4_0 --> 8.2-h8228510_1
  requests                              2.26.0-pyhd8ed1ab_0 --> 2.28.2-pyhd8ed1ab_1
  setuptools         conda-forge/linux-64::setuptools-58.0~ --> conda-forge/noarch::setuptools-67.6.1-pyhd8ed1ab_0
  tk                                      8.6.11-h27826a3_1 --> 8.6.12-h27826a3_0
  tqdm                                  4.62.3-pyhd8ed1ab_0 --> 4.65.0-pyhd8ed1ab_1
  tzdata                                   2021a-he74cb21_1 --> 2023c-h71feb2d_0
  urllib3                               1.26.7-pyhd8ed1ab_0 --> 1.26.15-pyhd8ed1ab_0
  wheel                                 0.37.0-pyhd8ed1ab_1 --> 0.40.0-pyhd8ed1ab_0
  xz                                       5.2.5-h516909a_1 --> 5.2.6-h166bdaf_0

Proceed ([y]/n)? y

Downloading and Extracting Packages
zstandard-0.19.0     | 373 KB    | ########################################################################## | 100% 
certifi-2022.12.7    | 147 KB    | ########################################################################## | 100% 
cffi-1.15.1          | 229 KB    | ########################################################################## | 100% 
cryptography-40.0.2  | 1.4 MB    | ########################################################################## | 100% 
jsonpointer-2.0      | 9 KB      | ########################################################################## | 100% 
requests-2.28.2      | 56 KB     | ########################################################################## | 100% 
ruamel.yaml-0.17.21  | 184 KB    | ########################################################################## | 100% 
pycparser-2.21       | 100 KB    | ########################################################################## | 100% 
idna-3.4             | 55 KB     | ########################################################################## | 100% 
pyopenssl-23.1.1     | 125 KB    | ########################################################################## | 100% 
pluggy-1.0.0         | 16 KB     | ########################################################################## | 100% 
charset-normalizer-3 | 44 KB     | ########################################################################## | 100% 
toolz-0.12.0         | 48 KB     | ########################################################################## | 100% 
conda-package-handli | 247 KB    | ########################################################################## | 100% 
zstd-1.5.2           | 410 KB    | ########################################################################## | 100% 
jsonpatch-1.32       | 14 KB     | ########################################################################## | 100% 
urllib3-1.26.15      | 110 KB    | ########################################################################## | 100% 
tqdm-4.65.0          | 86 KB     | ########################################################################## | 100% 
pysocks-1.7.1        | 19 KB     | ########################################################################## | 100% 
colorama-0.4.6       | 25 KB     | ########################################################################## | 100% 
conda-package-stream | 17 KB     | ########################################################################## | 100% 
pycosat-0.6.4        | 108 KB    | ########################################################################## | 100% 
conda-23.3.1         | 933 KB    | ########################################################################## | 100% 
boltons-23.0.0       | 296 KB    | ########################################################################## | 100% 
brotlipy-0.7.0       | 342 KB    | ########################################################################## | 100% 
ruamel.yaml.clib-0.2 | 140 KB    | ########################################################################## | 100% 
Preparing transaction: done
Verifying transaction: failed

EnvironmentNotWritableError: The current user does not have write permissions to the target environment.
  environment location: /opt/conda
  uid: 1000
  gid: 100

(studiolab) studio-lab-user@default:~/sagemaker-studiolab-notebooks$ 

**Expected behavior**
version 23 should be installed 

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**

**Comment by icoxfog417** [comment]
Thank you for reporting the issue. We are discussing this problem in the following issue. We will notify you when the update is released.

https://github.com/aws/studio-lab-examples/issues/160
