### ISSUE TITLE
Error when requesting a new account

### ISSUE THREAD

**Issue by GregLed** [aws/studio-lab-examples#213]
Hi All,

I'm trying to request a new account but I keep on getting this info "Something went wrong. Please try again later.". Is there any issue with the platform right now? 

Thanks,
Greg

**Comment by icoxfog417** [comment]
Our service works normally. But we do not offer the service in the specific countries. Please refer the following FAQ.

https://studiolab.sagemaker.aws/faq

**Comment by MicheleMonclova** [comment]
Are you getting this error with the CAPTCHA challenge? If so please try upgrading your browser or trying a different one.  We have seen some issues with an older version of FireFox.

**Comment by MicheleMonclova** [comment]
Can we close this ?

**Comment by icoxfog417** [comment]
Dear @GregLed , we close this issue but feel free if you still have the problem.

**Comment by jumpingoat** [comment]
The same for me and my country is not banned.

**Comment by umsee** [comment]
I tried everything for the past few days I haven't been able to access an instance once. I tried everything. I even deleted the account and made a new one which was approved once again. When I went to finish the registration in the link the same error occurs. It seems to be a backed error or something

**Comment by Leovaldez42** [comment]
I have tried the same things for the past few days I am not able to login to my account. I have changed the browser, cleared the cache tried login in incognito.

**Comment by JonathanMartinezB** [comment]
Also, a week ago the error occurred rarely when logging in, the captcha did not come up, and it was refreshing the page. But yesterday it doesn't let me log in anymore, I tried with other browsers and it didn't work either.

**Comment by icoxfog417** [comment]
For the recent issue about "Something went wrong. Please try again later.", we are handling this error in the following issue. Please refer to get the recent status and temporary solution.

https://github.com/aws/studio-lab-examples/issues/254

**Comment by ameer513** [comment]
Hi All,

I'm trying to request a new account but I keep on getting this info "Something went wrong. Please try again later.". Is there any issue with the platform right now?

Thanks,
Ameer Hamza
