### ISSUE TITLE
Python interpreter not the same in notebook and in terminal

### ISSUE THREAD

**Issue by wenh06** [aws/studio-lab-examples#218]
**Describe the bug**

The Python interpreter is not the same in the notebook and in the terminal.

In the notebook, it is `/home/studio-lab-user/.conda/envs/default/bin/python`, while in the terminal, it is `/home/studio-lab-user/.conda/envs/studiolab/bin/python`.

**To Reproduce**
1. type `!which python` and run in a cell in some notebook
2. type `which python` and hit enter in a terminal

**Expected behavior**
The Python interpreter in the notebook and in the terminal should coincide. Otherwise, one has to install a package inside a notebook and also in the terminal.

**Screenshots**

![image](https://github.com/aws/studio-lab-examples/assets/8778305/72d19dc6-35d1-4a90-a794-ed9bf6e3b5f3)

![image](https://github.com/aws/studio-lab-examples/assets/8778305/8a7aa499-c6a8-4e62-8633-985613b541c3)

**Desktop (please complete the following information):**
 - OS: [win11]
 - Browser [edge]
 - Version [latest]

**Additional context**
N/A

**Comment by icoxfog417** [comment]
Dear @wenh06 , thank you for letting us know the issue. We have already recognized this issue and dealing with it.

https://github.com/aws/studio-lab-examples/issues/212

**Comment by MicheleMonclova** [comment]
The work around is in https://github.com/aws/studio-lab-examples/issues/212

**Comment by Sandy4321** [comment]
sorry , there is no work around  in https://github.com/aws/studio-lab-examples/issues/212

**Comment by icoxfog417** [comment]
We close this issue.

Dear @wenh06 , please add comment to #212 if you would like to add more context for this phenomenon.
Dear @Sandy4321 , please install `matplotlib` in `default` environment.

**Comment by icoxfog417** [comment]
Dear @Sandy4321 
Here is the work around.
https://github.com/aws/studio-lab-examples/issues/212#issuecomment-1518458661

**Comment by cpkson** [comment]
@icoxfog417 if there is a workaround, can this be closed?

**Comment by wenh06** [comment]
> Dear [@Sandy4321](https://github.com/Sandy4321) Here is the work around. [#212 (comment)](https://github.com/aws/studio-lab-examples/issues/212#issuecomment-1518458661)

I know the workaround, but we have to switch the environment frequently (each time a new terminal is opened). Can we have a unified environment? After all, the space is limited (only 50G), so we typically do not want several environments.
