### ISSUE TITLE
After changing the CPU and GPU runtime limits.

### ISSUE THREAD

**Issue by bobbie7wei1998** [aws/studio-lab-examples#221]
After changing the CPU and GPU runtime limits.

Please modify the startup time instead of 24 hours and preferably UTC every day

So that I can use the available session at the time of the college lecture

My classmates and I struggle with running time because the lectures in the college are not at the same time every day

Please help me and my college classmates

In order to benefit from the service at the correct time

We thank you for your good cooperation with students and providing assistance to students free of charge

**Comment by icoxfog417** [comment]
Hi @bobbie7wei1998 , we are glad to here you and your classmates use Studio Lab. 
[We provide 4 CPU hours / session maximum 8 hours / day and 4 GPU hours / session masimum 4 hours / day](https://studiolab.sagemaker.aws/faq). 
Let us ask 2 questions to know your struggling situation. 

1. How long do you use CPU / GPU for your lecture?
2. How long does interval time between lecture and lecture? 

We recently decreased limit and we would like to know how this limit affects developer's experience.

**Comment by bobbie7wei1998** [comment]
I will explain more

Today the class started at 4:15 pm and I used the GPU

And tomorrow the lecture will start at 02:30 pm

It means that I will not be able to use the GPU before 04:15 PM

I hope you understand what I mean

**Comment by MicheleMonclova** [comment]
Bobbie, do you always need GPU? You should do your coding and testing in CPU and only when ready to launch a compute heavy job, switch to GPU.

**Comment by MicheleMonclova** [comment]
Also, how long is the class? If you start your GPU for 1-2 hours, then stop your instance, you will be able to run it for another 1-2 hours in the same 24-hour period.

**Comment by icoxfog417** [comment]
@bobbie7wei1998  As I believe you're now able to continue with your lecture. Please feel free to open a new issue if you have any other questions or concerns that come up. I'm here to help, so don't hesitate to reach out. Wishing you all the best with your lecture!
