### ISSUE TITLE
Download PyTorch_model.bin - Server failed

### ISSUE THREAD

**Issue by AkimParis** [aws/studio-lab-examples#222]
Hello everyone!

**Describe the bug**
After 3 hours of training a model on PyTorch, I am unable to download the model 400 MB. 
I got a "Failed to connect - Server" in a text file instead of the NLP model.

**To Reproduce**
1. Right-click on the pytorch_model.bin
2. Download

**Expected behavior**
Download directly the file... 

Thx!

**Comment by MicheleMonclova** [comment]
Looking -  can you tell us how much storage you have left?

**Comment by AkimParis** [comment]
Hey @MicheleMonclova,

Thank you for your help. Please found below the response... 

(studiolab) studio-lab-user@default:~$ df -h
Filesystem      Size  Used Avail Use% Mounted on
overlay          32G   20K   32G   1% /
tmpfs            64M     0   64M   0% /dev
tmpfs           7.8G     0  7.8G   0% /sys/fs/cgroup
shm             4.0G     0  4.0G   0% /dev/shm
/dev/nvme0n1p1   50G  9.8G   41G  20% /opt/.sagemakerinternal
/dev/nvme1n1     25G  8.7G   17G  35% /home/studio-lab-user
devtmpfs        7.8G     0  7.8G   0% /dev/tty
tmpfs           7.8G     0  7.8G   0% /proc/acpi
tmpfs           7.8G     0  7.8G   0% /sys/firmware

**Comment by icoxfog417** [comment]
Hi, sorry for inconvenience. If you need quick solution and have an AWS account, please try the following steps.

1. execute [aws s3 cp](https://awscli.amazonaws.com/v2/documentation/api/latest/reference/s3/index.html) to upload a file to S3 after [setting up configuration](https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-quickstart.html).
2. download a file from S3.

related issue: https://github.com/aws/studio-lab-examples/issues/190

**Comment by AkimParis** [comment]
Thank you Kubo-san for your reply. 

But I gave up on the credit card validation of AWS... ちょっと面倒くさい・・・

I will toy around again with Studio Lab when the bug is fixed. ; )

**Comment by AkimParis** [comment]
@MicheleMonclova @icoxfog417 

Any news about this issue? It's sad to test on AWS studio lab and not be able to download the model...

Thank you!

**Comment by MicheleMonclova** [comment]
Hi AkimParis, this is an issue that we have in the queue to fix.  The best work around is to upload the file into S3 in your AWS account.  I know you didn't want to create an account because of the credit card approval. But hopefully you understand that you will be able to leverage the AWS free tier so your credit card will not be charged.

**Comment by AkimParis** [comment]
@MicheleMonclova 

Thank you for your help. I subscribed to Google Colab Pro+. The simplicity of Google won it this time on the "hacky" AWS free tier. Maybe if AWS Studio Lab provides a similar product in the near future, I might switch. : ) 

Have a good day!

**Comment by icoxfog417** [comment]
We close this issue and continue to discuss comfortable disk access integrated to S3 at #178. 
Dear @AkimParis , we continue to improve Studio Lab and hope you to come back Studio Lab in future!
