### ISSUE TITLE
cublas.h and cublas_v2.h are missing in /usr/local/cuda-11.2/include/

### ISSUE THREAD

**Issue by bobqianic** [aws/studio-lab-examples#224]
**Describe the bug**
I opened a GPU machine and attempted to compile a C++ project. When I ran CMake, an error occurred.
```
-- The C compiler identification is GNU 9.4.0
-- The CXX compiler identification is GNU 9.4.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found Git: /usr/bin/git (found version "2.25.1") 
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Unable to find cublas_v2.h in either "/usr/local/cuda/include" or "/usr/math_libs/include"
-- Found CUDAToolkit: /usr/local/cuda/include (found version "11.2.152") 
-- cuBLAS found
-- The CUDA compiler identification is NVIDIA 11.2.152
-- Detecting CUDA compiler ABI info
-- Detecting CUDA compiler ABI info - done
-- Check for working CUDA compiler: /usr/local/cuda/bin/nvcc - skipped
-- Detecting CUDA compile features
-- Detecting CUDA compile features - done
-- CMAKE_SYSTEM_PROCESSOR: x86_64
-- x86 detected
-- GGML CUDA sources found, configuring CUDA architecture
-- Configuring done (2.5s)
CMake Error at CMakeLists.txt:358 (target_link_libraries):
  Target "test" links to:

    CUDA::cublas

  but the target was not found.  Possible reasons include:

    * There is a typo in the target name.
    * A find_package call is missing for an IMPORTED target.
    * An ALIAS target is missing.
``` 

**To Reproduce**
1. cmake any project using cublas
2. See error

**Expected behavior**
No error.

**Screenshots**
<img width="919" alt="image" src="https://github.com/aws/studio-lab-examples/assets/129547291/0ca0f33a-56fb-4595-8265-e78dfa2ca748">

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser Chrome
 - Version 114

**Comment by icoxfog417** [comment]
Thank you for using Studio Lab! As error message `CMakeLists.txt:358` suggests, could please refer the `CMakeLists` file?
If you find out this error is caused by Studio Lab environment, please raise a new issue.

**Comment by HyunggyuJang** [comment]
I suspect that
```
Unable to find cublas_v2.h in either "/usr/local/cuda/include" or "/usr/math_libs/include"
```
is the source of error.
I myself met this error also. @icoxfog417 can you open it? As this is on going issue.

**Comment by icoxfog417** [comment]
@HyunggyuJang Thank you for reporting the issue. Can you provides reproducible steps? We would like to know what kind of libraries / tools you are trying to install. We recommend to use `conda` to install the packages so some of the libraries may not work.

**Comment by HyunggyuJang** [comment]
Sure, since I’m out of office, I’ll rather write briefly, and will augment later if you find necessary. 

## Reproduction step
1. Clone [llama.cpp](https://github.com/ggerganov/llama.cpp) 
2. follows the instruction to build cublas supported version:  https://github.com/ggerganov/llama.cpp#cublas
3. Then will see an error, basically the same one as the issue content of this, originated from https://github.com/ggerganov/llama.cpp/blob/master/CMakeLists.txt#L316

**Comment by HyunggyuJang** [comment]
I believe I tried. Let me check it again ASAP!
