### ISSUE TITLE
new conda environment  creation is not working 

### ISSUE THREAD

**Issue by Sandy4321** [aws/studio-lab-examples#225]
pls help 
new conda environment  creation is not working 
i try to do as recommended 
by running 
$ conda env create --name my_environment python=3.9

![image](https://github.com/aws/studio-lab-examples/assets/11426119/dbb4bbec-27b8-477c-9976-1343c8d3cfc5)

but get error
(studiolab) studio-lab-user@default:~/sagemaker-studiolab-notebooks$ conda activate default
(default) studio-lab-user@default:~/sagemaker-studiolab-notebooks$ conda env create --name my_env_p310_july17  python=3.10

SpecNotFound: Invalid name, try the format: user/package

![image](https://github.com/aws/studio-lab-examples/assets/11426119/a5d4c61b-f363-44c6-be9d-490458b803d7)

**Comment by Sandy4321** [comment]
i try to create new environment from terminal 
![image](https://github.com/aws/studio-lab-examples/assets/11426119/33bd2597-68af-4164-b3b6-3c88d1dcfabd)

**Comment by MicheleMonclova** [comment]
I am looking into this.

**Comment by Sandy4321** [comment]
thanks

**Comment by Sandy4321** [comment]
any updates pls

**Comment by Sandy4321** [comment]
so unprofessional from AWS people !!!

**Comment by icoxfog417** [comment]
As I mentioned in the following issue, it is not Studio Lab but. Please refer how to use conda command at [Creating an environment with commands](https://docs.conda.io/projects/conda/en/latest/user-guide/tasks/manage-environments.html#id1)

https://github.com/aws/studio-lab-examples/issues/211

**Comment by DevManPGP** [comment]
Some tech people are so dumb. What part of "env" in Conda's specification do you not understand? Did you even look at the ops picture showing that env IS required? Only a fool would close a case because they don't want to deal with their own ignorance.

**Comment by smstaneva** [comment]
It might be good to remove 'env' from the command in the documentation at the following link: https://docs.conda.io/projects/conda/en/latest/commands/env/create.html
