### ISSUE TITLE
new notebook can not be created with new environment use after  new environment is created and activated in terminal

### ISSUE THREAD

**Issue by Sandy4321** [aws/studio-lab-examples#226]
new notebook can not be created with new environment use after  new environment is created and activated in terminal

![image](https://github.com/aws/studio-lab-examples/assets/11426119/5a5e3d90-d791-4ae9-857f-c4b23a4fc1d2)

![image](https://github.com/aws/studio-lab-examples/assets/11426119/44ec4325-ea70-4538-bf25-575684e9ba34)

in any case how to make new environment visible to use for new notebook

**Comment by Sandy4321** [comment]
![image](https://github.com/aws/studio-lab-examples/assets/11426119/44daa34d-0380-4cea-ba75-19f1cdd54781)

**Comment by Sandy4321** [comment]
new environment is not visible
![image](https://github.com/aws/studio-lab-examples/assets/11426119/6cb35fe3-9c2c-4595-a6ad-427f0637437b)

**Comment by Sandy4321** [comment]
it is not like example, since new environment is not visible 


https://github.com/aws/studio-lab-examples/blob/main/custom-environments/custom_environment.ipynb
![image](https://github.com/aws/studio-lab-examples/assets/11426119/5d5ea587-4747-493e-8d8f-63d29f25f3cf)

**Comment by Sandy4321** [comment]
may i need to activate new environment through console - console environment is not changed after activating in terminal
but how to   activate new environment through console?

![image](https://github.com/aws/studio-lab-examples/assets/11426119/89506ae2-d497-4083-b7b9-cddd9849d614)

**Comment by Sandy4321** [comment]
conda init bash is not working neither

kernel restart is not helping 
![image](https://github.com/aws/studio-lab-examples/assets/11426119/ddea57fd-e438-4dab-8bf4-367672b69fe6)

**Comment by Sandy4321** [comment]
![image](https://github.com/aws/studio-lab-examples/assets/11426119/129c42ff-4849-40cb-bc2a-fdba56604a14)

**Comment by Sandy4321** [comment]
ok I found answer in
https://docs.aws.amazon.com/sagemaker/latest/dg/studio-lab-use-manage.html
then your explanatoin in https://github.com/aws/studio-lab-examples/blob/main/custom-environments/custom_environment.ipynb
is wrong 
since 
conda install ipykernel
missed

![image](https://github.com/aws/studio-lab-examples/assets/11426119/1f10f732-1400-4e8d-8ad1-1ff17f9d6681)

and
![image](https://github.com/aws/studio-lab-examples/assets/11426119/f007ffe1-170b-4380-82a2-c99c54524f37)
and
![image](https://github.com/aws/studio-lab-examples/assets/11426119/5b7f396f-d1e3-44f7-a4e8-4451299f3c43)

**Comment by icoxfog417** [comment]
We close this issue. `ipykernel` is included to `environment.yml`.
