### ISSUE TITLE
Unable to request new account

### ISSUE THREAD

**Issue by donnaphatt** [aws/studio-lab-examples#227]
Unable to submit a new request for an account via this link "https://studiolab.sagemaker.aws/requestAccount".
The form always shows "Something went wrong, Please try again later." as shown in the below image.
![image](https://github.com/aws/studio-lab-examples/assets/63700023/81168795-7194-44e2-bb3e-a918a9faf40b)

Please help, Thanks.

**Comment by icoxfog417** [comment]
Thank you for trying Studio Lab! I confirmed request account process recently but it worked fine. Could you please check again by confirming email address or internet connection?

**Comment by donnaphatt** [comment]
It's good now, Thank you.

**Comment by anhquan0** [comment]
> Thank you for trying Studio Lab! I confirmed request account process recently but it worked fine. Could you please check again by confirming email address or internet connection?

Excuse me! I encounter same problem, I checked by confirming email address or internet connection but everything is OK! Can you help me?
