### ISSUE TITLE
Can't install opencv-python due to the lack of libgthread-2.0.so.0

### ISSUE THREAD

**Issue by topsy404** [aws/studio-lab-examples#23]
**Problem:**

Hi, I’m trying to install `opencv-python` but failed due to the lack of  `libgthread-2.0.so.0`.

I got the following error:
```
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
/tmp/ipykernel_324/571303353.py in <module>
----> 1 import cv2

~/.conda/envs/default/lib/python3.9/site-packages/cv2/__init__.py in <module>
      6 import sys
      7 
----> 8 from .cv2 import *
      9 from .cv2 import _registerMatType
     10 from . import mat_wrapper

ImportError: libgthread-2.0.so.0: cannot open shared object file: No such file or directory
```

**Solution:**
Is it possible to install ``libgthread-2.0.so.0` by following [this way](https://askubuntu.com/a/1072878).
``` 
apt-get update -y
apt-get install libglib2.0-0
```
BTW, It is possible to install some other common applications, such as `vim`.

**Comment by spirosdim** [comment]
I have the same problem, but as I saw it is not possible to use apt-get or sudo in aws sagemaker studio lab (due to admin rights). 
Any ideas?

**Comment by EmilyWebber** [comment]
Hi - to import install opencv please use `%pip install opencv-python`.

See this closed issue here: 
- https://github.com/aws/studio-lab-examples/issues/10

Also see this tutorial here: 
- https://programmerah.com/installing-opencv-python-in-docker-container-15489/

**Comment by topsy404** [comment]
Got it, thanks a lot!

**Comment by EmilyWebber** [comment]
You bet.
