### ISSUE TITLE
Automatic Run on Multi GPU?

### ISSUE THREAD

**Issue by daniel-satria** [aws/studio-lab-examples#232]
Hello

I'm new to AWS Studio..

I tried to run a model training on ml.p3.2xlarge notebook instance, which has 1 GPU Tesla V100 16GB. It takes 1 hour per epoch.
Then, with the same configuration I tried to run on ml.p3.8xlarge notebook instance, which has Multi-GPU; 4 Tesla V100 16 GB. Strangely, it takes 1 hour per epoch too.

I can't help but wonder why they both take the same amount of time to training, even 8xlarge has multiple GPU.
As far as I know, AWS will automatically run the training with Multi-GPU and the instance also cost higher.

Anyone could please enlighten me for this problem?
Thank you!

**Comment by icoxfog417** [comment]
Dear @daniel-satria , thank you for using AWS for your machine learning work. Here is the place for SageMaker **Studio Lab **, not for **Studio**. (Sorry for very similar product name!).

If you use PyTorch, [MULTI-GPU EXAMPLES](https://pytorch.org/tutorials/beginner/former_torchies/parallelism_tutorial.html) will be useful to use multiple GPU. The application code change is required to use multiple GPU.

**Comment by icoxfog417** [comment]
@daniel-satria Thank you for submitting this issue. I've gone ahead and closed it, as I believe the best way for you to move forward would be to try executing your code on SageMaker Studio. The SageMaker Studio environment is designed to provide a highly scalable  and optimized experience for running your code. Please let me know if you have any questions or need further assistance in setting up SageMaker Studio. I'm here to help!
