### ISSUE TITLE
Not sending phone verification code

### ISSUE THREAD

**Issue by GUnd4m1** [aws/studio-lab-examples#233]
**Describe the bug**
Sagemaker not sending the phone verification code i need to start a runtime its been days already

**Comment by icoxfog417** [comment]
Could you please check the [FAQ: Why did I get an error when I entered my phone number section](https://studiolab.sagemaker.aws/faq)? Some kinds of number format is not supported in Studio Lab.

https://github.com/aws/studio-lab-examples/issues/159

**Comment by icoxfog417** [comment]
Thank you for reporting this issue. We appreciate you taking the time to provide feedback.

Upon reviewing the issue, it appears there may be a formatting issue with the phone number provided. Could you please double-check the phone number format? 

https://studiolab.sagemaker.aws/faq

> There may be several causes to this error: Make sure the number is in an [E.164 format](https://www.itu.int/rec/T-REC-E.164/en), and that it is not a VoIP or landline number. If the phone number meets those requirements but you still get the error, wait a few minutes and try again.

Please feel free to reach out if you have any other questions or concerns. We're here to help and look forward to working with you to resolve this matter.
