### ISSUE TITLE
There is no runtime available right now. Please change the compute type or try again later.

### ISSUE THREAD

**Issue by ObsidianMC123** [aws/studio-lab-examples#234]
**Describe the bug**

**To Reproduce**
1. Go to 'web'
2. Click on 'gpu'
3. Click on 'startruntime'

**Expected behavior**

**Screenshots**
![image](https://github.com/aws/studio-lab-examples/assets/76558667/38e6b31b-232e-4732-9fcf-d404049a70db)

**Desktop (please complete the following information):**

**Additional context**

**Comment by lvsh2012** [comment]
me too

**Comment by icoxfog417** [comment]
Thank you for bringing this issue to our attention. We understand the challenges you're facing with limited computing resources, and we're working hard to find a solution. Please bear with us as we explore ways to address this concern. We appreciate your patience and understanding as we work to improve the product for all our users.
