### ISSUE TITLE
Unable to login account

### ISSUE THREAD

**Issue by Jjubin119** [aws/studio-lab-examples#237]
I can't log in with the statement "Something went wrong. Please try again later." with the link https://studiolab.sagemaker.aws/login

![Sagemaker](https://github.com/aws/studio-lab-examples/assets/150496064/a3054a47-d5e7-47bf-8042-9c4fc8ea4386)

Please help me deal with this because it has been dragging on for days

**Comment by icoxfog417** [comment]
Hello, we appreciate your use of Studio Lab, and we sincerely apologize for any inconvenience you've experienced. Is this error occurring consistently, or is it an intermittent issue?

**Comment by eza02** [comment]
hai i have problem issue about that, and this error occurring consistently.
you can check on my issue

**Comment by MicheleMonclova** [comment]
Hi, need more details:
1. have you ever been able to log in?
2. have you ever verified your account with a mobile phone
3. have you ever passed the CAPTCHA successfully.
4. Did you get any email from studiolab indicating something is wrong with your account?
Thanks!

**Comment by eza02** [comment]
Hi, need more details:

1.have you ever been able to log in?
   - yes i have but not in sameday sometimes 
   
2. have you ever verified your account with a mobile phone
   -  yes i have if not verified with mobile number how i can using that platform
   
3. have you ever passed the CAPTCHA successfully.
   -  always successfully
   
4. Did you get any email from studiolab indicating something is wrong with your account?
   -  No, last email from studiolab is your account is already.
Thanks!

**Comment by MicheleMonclova** [comment]
It looks like you never verified with a mobile? please use this link to send me your user name privately on Studio Lab and we can look you up. https://pages.awscloud.com/GLOBAL_PM_PA_amazon-sagemaker_20211116_7014z000000rjq2-registration.html

**Comment by Xandarronan** [comment]
same happening with me

**Comment by MicheleMonclova** [comment]
Xandarronan - have you ever been able to verify your mobile? Please tell me more details.

**Comment by JetClark** [comment]
Same with me, sometime it is happen

I have my mobile phone number verified, and even the captcha. Sadly, the error always happen when i am need in hurry, but when i use for study or in relaxing time, it never get error like above

**Comment by icoxfog417** [comment]
We close this issue because of no response from original user. Please raise the additional issue if you encounter the trouble.

**Comment by rgadodia** [comment]
I added the issue details to the web page as listed above
https://pages.awscloud.com/GLOBAL_PM_PA_amazon-sagemaker_20211116_7014z000000rjq2-registration.html

I was never asked to verify a mobile number as part of registration.
