### ISSUE TITLE
Cannot install apex nvidia in sagemaker studio Lab

### ISSUE THREAD

**Issue by mobulan** [aws/studio-lab-examples#24]
**Is your feature request related to a problem? Please describe.**
the default cuda version is 11.2, but there is no match pytorch version with cuda 11.2, may be 11.1 or 11.3 can work
**Describe the solution you'd like**
when install apex, i face the problem of the dismatch version of pytorch and cudatoolkit
**Describe alternatives you've considered**
can you provide different version of cuda, or preinstall all the popular versions, such as 10.2,11.1,11.3 and so on
**Additional context**

**Comment by samx18** [comment]
Thanks for trying out Studio Lab! I have installed packages that cudatoolkit as a dependency. It installed 11.3. Are you referring this https://github.com/NVIDIA/apex?

**Comment by mobulan** [comment]
please check my studio, the account is txvxdx@me.com
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/41856770/146208342-77fea186-2096-4819-bd81-26f88f3ea4c8.png">

**Comment by samx18** [comment]
Hi @mobulan, Even though you can install a different cudatooklit version in a custom conda environment, it is not possible to upgrade the system CUDA drivers via conda. I will log a enhancement request to upgrade the system CUDA drivers.

**Comment by mobulan** [comment]
﻿
﻿yes，this is the key question, apex doesn’t allow different version between PyTorch and CUDA. So I can only wait your upgrade now

发自莫布兰的 iPhone



发自莫布兰的 iPhone

**Comment by samx18** [comment]
Add this the next feature release. Closing this issue.

**Comment by DataDrover** [comment]
Two years later, it looks like  the nvidia drivers are still on the same version. Time for an update?

**Comment by Saradominist** [comment]
> Two years later, it looks like the nvidia drivers are still on the same version. Time for an update?

I've also been waiting for them to update their drivers, there's no pytorch version that currently supports both the current driver and my code

**Comment by robinmonjo** [comment]
Waiting on my side as well, need at least cuda 11.8 😢

**Comment by benjats07** [comment]
In my case I need CuDNN installed but no way to do it without root password or sudo. Anyone have found a way to install it?

**Comment by MicheleMonclova** [comment]
Thank you gentlemen for your feed back. have you looked into the sagemaker distribution image?
announcement:
https://aws.amazon.com/about-aws/whats-new/2023/08/amazon-sagemaker-studio-lab-supports-sagemaker-distribution/
documentation:
https://docs.aws.amazon.com/sagemaker/latest/dg/studio-lab-use-manage.html
