### ISSUE TITLE
Kernal getting died after every few minutes with simple code of execution

### ISSUE THREAD

**Issue by itsmerajat** [aws/studio-lab-examples#244]
**Describe the bug**
While running basic Python CPU code, the kernel dies and due to this not able to work here.

**To Reproduce**

**Expected behavior**

**Screenshots**
<img width="340" alt="image" src="https://github.com/aws/studio-lab-examples/assets/114578716/06ee3694-4936-4447-99f3-8fd5d6beaa06">

**Desktop (please complete the following information):**

**Additional context**

**Comment by icoxfog417** [comment]
Hi, thank you for reporting the issue.

> While running basic Python CPU code

Do you mind sharing the code in this issue? We need it to find the root cause.

**Comment by icoxfog417** [comment]
@itsmerajat 
Thank you for reporting this issue. I've tried the CPU mode and I assume the problem has been resolved. If you're still experiencing any difficulties, please feel free to reopen the issue. I'm here to help and want to ensure you have a positive experience. Have a great day!
