### ISSUE TITLE
Receiving a 500: Internal Server Error when opening my project after selecting cpu runtime

### ISSUE THREAD

**Issue by rchow93** [aws/studio-lab-examples#246]
**Describe the bug**

**To Reproduce**
1. Go to 'Start Runtime (CPU)'
2. Click on 'Open Project'
3. Scroll down to 'launches browser to open runtime'
4. See error: Receive a 500: Internal Error

**Expected behavior**
Should launch my normal runtime.

**Screenshots**
<img width="751" alt="Screenshot 2023-12-29 at 11 31 45 PM" src="https://github.com/aws/studio-lab-examples/assets/4554120/9943dc34-7d97-478a-9f2d-cff73108d532">

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Mac OS
 - Browser [e.g. chrome, safari] Chrome

**Additional context**
Is there a way to reset the runtime back to the original state.

**Comment by icoxfog417** [comment]
Do you get a 500 error from the beginning? If you made some changes before you got this error, deleting and recreating the account is a workaround to reset the environment.

**Comment by icoxfog417** [comment]
@rchow93 Hello, I hope this message finds you well. I noticed that the issue you previously reported has not been resolved. If you are still experiencing the same problem, please feel free to let us know, and we will be happy to assist you further. We appreciate your patience and look forward to helping you resolve this matter.
