### ISSUE TITLE
"You can't use the project runtime because your account is associated with activity that may have violated our Service Terms."

### ISSUE THREAD

**Issue by GatehackerR81** [aws/studio-lab-examples#248]
**Describe the bug**

**To Reproduce**
1. Go to my Sagemaker Studio Lab project
2. Click on Start runtime (GPU)
3. See error "You can't use the project runtime because your account is associated with activity that may have violated our Service Terms"

**Expected behavior**
Runtime started or "too busy to grant runtime" error.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Brave

**Additional context**
I really have no clue about what terms I could've violated. I checked the FAQ multiple times but I just don't see why I would get banned. Is there a way to contact Sagemaker Studio Lab's support? I don't know of any other tools similar to this one and free.
Thanks.

**Comment by MicheleMonclova** [comment]
Hi Gatehacker, please send me your SageMaker user id here and I will look into it.
https://pages.awscloud.com/GLOBAL_PM_PA_amazon-sagemaker_20211116_7014z000000rjq2-registration.html

**Comment by GatehackerR81** [comment]
Hello. I sent you my ID.

**Comment by icoxfog417** [comment]
We've gone ahead and closed this issue. I hope @GatehackerR81 is able to resolve the problem by providing the ID. Please feel free to reopen the issue if you need any further assistance.
