### ISSUE TITLE
Notebook not rendering properly in Chrome or Edge

### ISSUE THREAD

**Issue by MarkRoss-Eviden** [aws/studio-lab-examples#249]
**Describe the bug**
Notebook not rendering correctly in Edge or Chrome, so as to be unusable

**To Reproduce**
1. Go to 'Open Project'
2. Wait for page to load

Note - this wasn't an issue when I first signed up, but every time I open my notebook now it is

**Expected behavior**
Show Jupyter notebook properly rendered

**Screenshots**
Chrome: -
![image](https://github.com/aws/studio-lab-examples/assets/53598199/fe53ec1a-5eef-4769-ac14-7dd6eae32984)

Edge: -
![image](https://github.com/aws/studio-lab-examples/assets/53598199/5da85f3d-8c4e-4cd4-9f3a-a23533e25238)

**Desktop (please complete the following information):**
 - OS: [Windows 10]
 - Browser [Chrome]
 - Version [121.0.6167.189]
 -
 - OS: [Windows 10]
 - Browser [Edge]
 - Version [122.0.2365.52]

**Additional context**
The issue only started happening after I'd been using the notebook successfully for a few hours.  It previously rendered fine in Chrome.
I've tried shutting down the notebook
I've tried clearing my browsing cache to a time before I used the notebook for the first time
I've tried adding ?reset to the end of my url

**Comment by MicheleMonclova** [comment]
Hi, I just tested on  FireFox and and MSFT Edge Microsoft Edge Version 122.0.2365.52 (Official build) (64-bit)
Looks fine. As soon as i can recreate I will log a bug for engineering

**Comment by icoxfog417** [comment]
@MarkRoss-Eviden Thank you for using the Studio Lab! Do you still have the trouble? Is this issue still reproducible?

**Comment by MarkRoss-Eviden** [comment]
Currently unable to reproduce
