### ISSUE TITLE
Studio Lab Sign up does not work

### ISSUE THREAD

**Issue by dn4086** [aws/studio-lab-examples#25]
I received an email from Sagemaker Studio Lab team that I was approved for an account couple of days ago. I tried multiple times to sign up, but it says the information is incorrect or the approval is expired. I am using the same email I used to request a free account and I tried to sign up the day I received the approval and I tried it today and I have still no luck. I don't know where else to turn to because there is no help form.

**Comment by ellisonbg** [comment]
This is the right place to report this, someone will investigate.

**Comment by MicheleMonclova** [comment]
Hi, once you are approved you have 7 days to register. If you don't we expire your approval. We do this because the service is very popular and we want to make sure we are prioritizing folks that are active.  If your approval has expired simply request an account again.

**Comment by dn4086** [comment]
@MicheleMonclova Yes, I understand it expires within 7 days if not registered. My issue was, I tried to register the same day I received my approval email, but it still told me it was expired.

**Comment by MicheleMonclova** [comment]
I heard of one other case like this - let me investigate. Thank you for your patience.

**Comment by MicheleMonclova** [comment]
@dn4086 can you fill out this form. https://pages.awscloud.com/GLOBAL_PM_PA_amazon-sagemaker_20211116_7014z000000rjq2-registration.html  Here you can safely put in your email address that you are having issues with.

**Comment by dn4086** [comment]
@MicheleMonclova 
Thanks. Just submitted the form.

**Comment by MicheleMonclova** [comment]
Hi  - you should have received another email yesterday to help you complete your registration. Did you?

**Comment by dn4086** [comment]
Hi @MicheleMonclova ,
I did not receive an email from AWS. I did check my spam too. is there a way you can re-send it?

**Comment by MicheleMonclova** [comment]
Hi  Dn4086 - according to our logs your final email verification keeps timing out, requiring to start over. Sorry. Let us know if you are having better luck.
