### ISSUE TITLE
Registered for aws sagemaker studio but not able to create account

### ISSUE THREAD

**Issue by RejwanShafi** [aws/studio-lab-examples#259]
Hi I received my aws sagemaker studio approval to create an account Yesterday.  It always says something wen wrong please try again later. I am from Bangladesh.

Please sort this out.

**Comment by icoxfog417** [comment]
Thank you for your patience. We are investigating this issue. We would like to designate a single point of contact, therefore, we will be closing this issue. Please watch the following issue to monitor the progress.

https://github.com/aws/studio-lab-examples/issues/254
