### ISSUE TITLE
Cant download big model trained files from Studio lab

### ISSUE THREAD

**Issue by gauravbrills** [aws/studio-lab-examples#26]
**Describe the bug**
cannot download big files from sudio lab
**To Reproduce**
Download a file bigger than 250 mb from studio jupyterlab folder

**Expected behavior**
Big files should get downloaded just like in similar env like collab and kaggle 

Even when trying curl I get

```
curl https://foo.studio.us-east-2.sagemaker.aws/studiolab/default/jupyter/files/jigsaw/jg-model.bin?_xsrf=2%7C5be63d77%11%7C1639414836
Invalid or Expired Auth Token. Request a new presigned URL to continue using SageMaker.
```

**UPDATE**

It sometimes does download but mostly when I try saving the big files it gives a download error

**Comment by ellisonbg** [comment]
The error message you are seeing there looks like your 12 or 4 hour session had expired. Can you relaunch your project and try again?

**Comment by gauravbrills** [comment]
Hi @ellisonbg  I did think that but still getting issues when downloading large models [250mb +] directly from studio/jupyter lab . For now I resorted to directly uploading to git and s3/gcs . 

Did try this on an active session as well (GPU) with 35 mins left . First of all the download **saveAs** comes after a long time and when I click to save it locally it just throws a [**Network Error**] . Not sure I am the only one facing this.

**Comment by pymia** [comment]
I tried to reproduce with a 300mb+ single file upload and download in Studio Lab.
If you download by right click, select Download. It should work.

I also don't have the answer for `Invalid or Expired Auth Token. Request a new presigned URL to continue using SageMaker.`
I've created an internal ticket for this bug.

**Comment by gauravbrills** [comment]
@pymia did the same not sure why it didn't work .. Could be a browser thing also will give a try again but for now uploading via cloud storages seems easier to me .
