### ISSUE TITLE
"Something went wrong, please try again later"

### ISSUE THREAD

**Issue by AdamPrzychodniPrivate** [aws/studio-lab-examples#260]
<img width="1207" alt="Screenshot 2024-04-19 at 13 47 57" src="https://github.com/aws/studio-lab-examples/assets/126712843/a4c5e9d5-caa0-4ae1-8152-bce7e700869e">
Hi :) 

I have an issue with my workspace I cannot access the project after, couple hours of trying.

Best regards,
Adam

**Comment by bekahose** [comment]
![image](https://github.com/aws/studio-lab-examples/assets/105871191/dadf8de5-8905-4b99-b802-a543a055b123)

already error

**Comment by bekahose** [comment]
i try 3 hours, same error.

**Comment by lordtrump** [comment]
same issue, I've tried restarting the router or clearing the cache
This started two days ago, but now it's worse

**Comment by DwyaneSkala** [comment]
Same, can't login
![2024-04-19_173107](https://github.com/aws/studio-lab-examples/assets/96664249/5b7052c9-2c99-4c79-8348-ff570921bb7b)
Something went wrong. Please try again later.

**Comment by bekahose** [comment]
I think it's aws waf problem

**Comment by icoxfog417** [comment]
Thank you for your patience. We are investigating this issue. We would like to designate a single point of contact, therefore, we will be closing this issue. Please watch the following issue to monitor the progress.

https://github.com/aws/studio-lab-examples/issues/254
