### ISSUE TITLE
"Something went wrong. Please try again later" error displayed instead of Captcha window

### ISSUE THREAD

**Issue by AlichinoML** [aws/studio-lab-examples#261]
Hello, AWS team

**Describe the bug**
I'm trying to start a project in SageMaker Studio Lab using GPU. Instead of displaying Captcha and starting project like usual it throws error "Something went wrong. Please try again later". This issue started aroud 5-6 days ago and is intermittent. After trying several times it works but today the issue got worse.

I've tried in Firefox and Chrome browsers.

In web developer console I can see 405 "Cors allow origin not matching origin" error 3 times and response "Javascript is disabled... The CAPTCHA puzzle requires javascript" See screensot below. Java Script is enabled and after several retries Captcha window appears but not today.

![cors_error](https://github.com/aws/studio-lab-examples/assets/167549416/6d22a9cf-0f44-4d9d-af74-5da32a4a3cac)

**Comment by bekahose** [comment]
chorme ?

**Comment by AlichinoML** [comment]
There are similar extensions for Chrome although I didn't try them. Also you can try to run Chrome from command line with --disable-web-security key as suggested in other bug thread here.

**Comment by realmeraja** [comment]
> Workaround for Firefox:
> 
> 1. Install "CORS Everywhere" extension
> 2. Enable it before starting project (Enable/Disable button is in the Extensions list on toolbar)
> 3. Disable it after starting project

This is working :) i tried just now. its working perfectly. Thanks to [AlichinoML](https://github.com/AlichinoML)

**Comment by Darkreep** [comment]
> chorme ?

I use the [Allow Cors extension](https://chromewebstore.google.com/detail/allow-cors-access-control/lhobafahddgcelffkeicbaginigeejlf?hl=es) and it worked fine

**Comment by lordtrump** [comment]
> > chorme ?
> 
> I use the [Allow Cors extension](https://chromewebstore.google.com/detail/allow-cors-access-control/lhobafahddgcelffkeicbaginigeejlf?hl=es) and it worked fine

thank you

**Comment by icoxfog417** [comment]
Thank you for your patience. We are investigating this issue. We would like to designate a single point of contact, therefore, we will be closing this issue. Please watch the following issue to monitor the progress.

https://github.com/aws/studio-lab-examples/issues/254
