### ISSUE TITLE
Would the GPU execution time will restart? ?

### ISSUE THREAD

**Issue by RejwanShafi** [aws/studio-lab-examples#262]
I have been also facing the problem I trained my model halfway yesterday and thought the remaining GPU time would restart today as well. After yesterday's training, I had only 45 mins left for GPU usage. Will it get renewed today?

As I need more time to train the model efficiently and then validate and predict using my model?

![image](https://github.com/aws/studio-lab-examples/assets/147076527/44630100-f071-4408-a480-5a194d1b6752)

**Comment by kadalio3** [comment]
as i know is 24 hours after u started it, just write what time u started it

**Comment by icoxfog417** [comment]
Thank you @kadalio3 , the GPU time restarts after 24 hours. If you cannot get next 4 hours despte 24 hours, please let us know.

**Comment by RejwanShafi** [comment]
Thanks it worked . Though instead of 24 hours I had to wait 26 hours.
