### ISSUE TITLE
Unable to request account

### ISSUE THREAD

**Issue by TheYoungBaller** [aws/studio-lab-examples#266]
Error message "Something went wrong, please try again later" while requesting an account, it's not the CORS problem and when i tried using the disabled security browser version, another error message "this email is not allowed" pop out even though im using my two organization email and the results are the same

**Comment by MicheleMonclova** [comment]
Sorry for the inconvenience.  Can you please use this form to give us more information privately, such as the email address that you tried.

**Comment by TheYoungBaller** [comment]
sure

**Comment by MicheleMonclova** [comment]
Are you still getting this error? can you please upload a screenshot of the error.

**Comment by TheYoungBaller** [comment]
Thank you for reaching out, finally im able to request an account smoothly
