### ISSUE TITLE
Unable to create an account

### ISSUE THREAD

**Issue by avcode-exe** [aws/studio-lab-examples#267]
**Describe the bug**
I am unable to create an account in SageMaker studio lab.

**Screenshots**
![图片](https://github.com/aws/studio-lab-examples/assets/88149772/31afe84e-dd42-4354-81b3-baefb0ba8e58)

**Desktop (please complete the following information):**
 - OS: Windows 11 23H2
 - Browser Firefox
 - Version 126

**Additional context**
I have read other issues and found out I may need to use a command but that is for chrome. I would like to know how to solve the issue on Firefox.

Thanks in advance!

**Comment by MicheleMonclova** [comment]
I use firefox and never had an issue.  
I just tested with an email that already has an account and it worked
I tested with an account that has already requested one and it works.
I am using version 115.11.0 on firefox though. ;/
Can you go here and tell me (securely) https://pages.awscloud.com/GLOBAL_PM_PA_amazon-sagemaker_20211116_7014z000000rjq2-registration.html
1/ email you are trying
2/ IP address
3/ your country / location

**Comment by avcode-exe** [comment]
Some how the issue resolve.
