### ISSUE TITLE
Can't upload dataset to Lab

### ISSUE THREAD

**Issue by liusiyuxyfx** [aws/studio-lab-examples#29]
The FAQ says there are 15GB space for us, but I can't even upload or download a 900MB DataSet.
When I upload or download it, return ""
```
Unexpected error while saving file: sagemaker-studiolab-notebooks/preprocessed20152019.zip [Errno 2] 
No such file or directory: 
'/home/studio-lab-user/sagemaker-studiolab-notebooks/.~preprocessed20152019.zip'
 -> '/home/studio-lab-user/sagemaker-studiolab-notebooks/preprocessed20152019.zip'
```
sometimes it returned "no space"

**Comment by pymia** [comment]
Do you upload file with "Upload Files" or from Terminal?
Can you share more detail? Thanks.

**Comment by EmilyWebber** [comment]
Hi - since we haven't heard from you in a few weeks I'm closing this issue. Please re-open if the need arises.
