### ISSUE TITLE
Kernel Restarting Automatically at same code block in the entire notebook

### ISSUE THREAD

**Issue by chaundhyan** [aws/studio-lab-examples#33]
**Describe the bug**
I'm constantly getting an error saying the kernel is restarting automatically. And it is happening at the same code block in the entire notebook.

**To Reproduce**
Steps to reproduce the behaviour:
Code block where the error is occurring:

```
X_train = sequence.pad_sequences(features_train.todense(), maxlen=100)
X_test = sequence.pad_sequences(features_test.todense(), maxlen=100)
```

Prior Code:
```
#%pip install keras
#%pip install tensorflow

from keras.models import Sequential
from keras.layers import Dense
from keras.layers import LSTM
from keras.layers.embeddings import Embedding
from keras.preprocessing import sequence
```

Prior to that, I've done some data cleaning, stop words, lemmetizing, etc.
Then created a TF-IDF using ngram-range(1,2)
Then I'm trying to do the classification by different algos.
Naive Bayes is executing well.
MLP is also executing well.
Then I'm trying to do LSTM (RNN).
During that, I'm getting error.

**Expected behaviour**
It should execute well, without any error

**Screenshots**
![Screenshot 2021-12-20 at 10 24 33 PM](https://user-images.githubusercontent.com/25224230/146803629-24e4c945-1603-4dd0-a3f8-6ae0605acd52.png)

**Desktop (please complete the following information):**
 - OS: [MacOS Monetary v12.0.1 (21A559)]
 - Browser [Chrome]
 - Version [Version 96.0.4664.110 (Official Build) (x86_64)]

**Comment by EmilyWebber** [comment]
Hi - this is very strange, I will investigate.

**Comment by samx18** [comment]
We have seen this behavior when you run out of space. I suspect the below code block might be causing the space issue. Could you try adjusting the data or the `maxlength`? 
```
X_train = sequence.pad_sequences(features_train.todense(), maxlen=100)
X_test = sequence.pad_sequences(features_test.todense(), maxlen=100)
```

**Comment by samx18** [comment]
Closing this as this is likely due to space constraints. Please feel free to re-open if the issue persists.
