### ISSUE TITLE
How to permenantly delete the files?

### ISSUE THREAD

**Issue by seanbenhur** [aws/studio-lab-examples#35]
I got out of space error, even though i deleted the files multiple times, Can you tell me how to permenantly delete the files

**Comment by npmajisha** [comment]
The default behavior of jupyter is to move the deleted files to platform trash bin. You will find the deleted files in this location
_/home/studio-lab-user/.local/share/Trash/files_ . Deleting files using _rm_ will permanently delete them.

Thanks for reporting this issue, we will look into updating the Jupyter server setting to permanently delete files.

**Comment by seanbenhur** [comment]
Thanks for the prompt response, this works, I will close the issue
