### ISSUE TITLE
Ran out of storage, now unable to delete files

### ISSUE THREAD

**Issue by harish5p** [aws/studio-lab-examples#36]
**Describe the bug**
I ran out of storage when I downloaded files, since then I cannot start a kernel. When I tried to delete the files I downloaded, I get "Delete Failed unhandled error". Is there a way to delete files?

**Desktop (please complete the following information):**
 - Windows OS
 - **Firefox Browser**

**Comment by npmajisha** [comment]
Hello,

This issue may be similar to https://github.com/aws/studio-lab-examples/issues/35#issuecomment-1001746976

Q. How are you deleting the files? Have you also deleted files from this location - `/home/studio-lab-user/.local/share/Trash/files` 

The default behavior of jupyter is to move the deleted files to platform trash bin. You will find the deleted files in this location `/home/studio-lab-user/.local/share/Trash/files` . Deleting files in this location using rm will permanently delete them.

Can you try to delete the files from this location, and see if issue persists?

**Comment by harish5p** [comment]
I right-clicked on a folder to delete it, then I get the above mentioned error. I cannot open any kernel due to storage issue, how do you suggest I delete files?

**Comment by szamarin** [comment]
Are you able to access the terminal (File -> New -> Terminal)? If so you can use that to delete unwanted data using rm. Try running this command ` rm -rf <path_to_directory>`
