### ISSUE TITLE
Allow to recreate the entire machine

### ISSUE THREAD

**Issue by robmarkcole** [aws/studio-lab-examples#42]
**Is your feature request related to a problem? Please describe.**
After attempting to free up space using `rm -rf .*` I have also deleted files required by conda. I've partially recovered the situation but clearly the machine is a bit of a mess now, and I have this issue https://github.com/jupyter/notebook/issues/5321 I would like to do a hard reset to a clean machine, but this doesn't appear possible. Im facing the possibility of having to create a new account just to get a clean machine

**Describe the solution you'd like**
A menu option to reset/clean the machine. Also whilst at it, some UI to see how the 15GB are used would be useful

**Describe alternatives you've considered**
Na

**Additional context**
Na

**Comment by samx18** [comment]
Thanks for trying out SageMaker Studio Lab! We will log this enhancement request. Meanwhile as a workaround, removing the `.conda` and `.cache` folders cleans up most of the packages while enabling the the studio lab environment to recover gracefully.

**Comment by adalseno** [comment]
Hi @robmarkcole to free space you may also revert [conda](https://docs.conda.io/projects/conda/en/4.6.0/_downloads/52a95608c49671267e40c689e0bc00ca/conda-cheatsheet.pdf) to previous state
```
conda list --revisions              #this will show all revision numbers and package changes
conda install --revision n       #where n is the revision number to revert back
```

 and/or run `conda clean --all` (this one will delete cached packages and unused ones, freeing up a lot of space, see [doc](https://docs.conda.io/projects/conda/en/latest/commands/clean.html))
