### ISSUE TITLE
Cannot install/run docker

### ISSUE THREAD

**Issue by EyalSeg** [aws/studio-lab-examples#43]
**Is your feature request related to a problem? Please describe.**
Hello!
I tried running the code from [this repository](https://github.com/uber-research/deep-neuroevolution) but the script failed because it depends on tmux. as I understand it, currently there's no possibility to install tmux myself since I don't have root access. Since they expose a docker container I though about running through that, but had no success doing so. Is docker available?

**Describe the solution you'd like**
The ability to run docker commands through the terminal. Perhaps even integration with the docker desktop ui?

**Describe alternatives you've considered**
I tried installing docker myself, or the dependencies the repository needed. Both failed

**Comment by EmilyWebber** [comment]
Hello - yes we are aware of this as a known feature enhancement. Thanks for your feedback!

**Comment by EmilyWebber** [comment]
Closing this as the issue is known and we are tracking.
