### ISSUE TITLE
Calling tensorboard from notebook results in timeout.

### ISSUE THREAD

**Issue by MarkB2** [aws/studio-lab-examples#44]
**Describe the bug**
Calling tensorboard from notebook results in timeout.

**To Reproduce**
1. Install pytorch `%conda install pytorch torchvision torchaudio cudatoolkit=11.3 -c pytorch`
2. Open new notebook, insert cell 
`! mkdir -p output`
`%load_ext tensorboard`
`%tensorboard --logdir output`
`
3. Jupyter outputs  "Launching tensorboard ..." and waits for xxx.studio.us-east-2.sagemaker.aws 
4. After some minutes I get xxx.studio.us-east-2.sagemaker.aws took too long to respond 
5. After some unsuccessful attempts Jupyter loose connection to server.

**Expected behavior**
The very same notebook on local installation and on Colab shows empty Tensorboard.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Chrome
 - Version  96.0.4664.110 

**Additional context**

**Comment by alaknan** [comment]
@MarkB2 I followed the steps you have provided above and I am not able to reproduce the issue. I had to include tensorboard installation as well to your  %conda install. I get the expected behavior you have stated above. Can you please re-try and let me know if you still see the same issue?

**Comment by MarkB2** [comment]
I still can't run tensorboard extension *from inside* a notebook, but I can run tensorboard in terminal and then it's possible to point browser to https://<my aws url without *lab*>/proxy/6006/ and see tensorboard output (as described [here](https://docs.aws.amazon.com/sagemaker/latest/dg/studio-tensorboard.html).     
If this a supposed method it should be mentioned somewhere.

**Comment by alaknan** [comment]
@MarkB2 You can launch tensorboard from both notebook and terminal. But you can view the tensorboard ui only from the browser. I am able to reproduce the "took too long to respond" error inside the notebook, however it does launches tensorboard that can be accessed from a browser. I will pass this feedback to the service team.

**Comment by icoxfog417** [comment]
@EmilyWebber , I confirmed that TensorBoard is not worked in Notebook. The issue reported from @MarkB2 may not be solved. Should we re-open this issue?
