### ISSUE TITLE
ImportError: libgthread-2.0.so.0: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by DL-stack** [aws/studio-lab-examples#45]
**Describe the bug**
After I created a new conda env on studiolab and installed the necessary modules for my project I am now stuck at the following error message 

   import cv2
  File "/opt/conda/envs/pytorch-py3.6/lib/python3.6/site-packages/cv2/__init__.py", line 3, in <module>
    from .cv2 import *
ImportError: libgthread-2.0.so.0: cannot open shared object file: No such file or directory

After looking this error up, the only solution seems to be 
apt-get update 
apt-get install libglib2.0-0

However  I do not have the permissions on studiolab for running these commands.
How can I solve this issue, is there another way?

**Comment by alaknan** [comment]
I am able to replicate the permission issue that you have mentioned using pip install. I am able to get the import statements to work by installing opencv using "conda install -c conda-forge opencv " Can you please try this?
