### ISSUE TITLE
no space ，and  can not start the project  ,how to solve the problem  

### ISSUE THREAD

**Issue by gaoyuan211** [aws/studio-lab-examples#48]
no space ，and  can not start the project  ,how to solve the problem  

my acount si   66212664@qq.com

**Comment by gaoyuan211** [comment]
There was a problem when starting the project runtime. This should be resolved shortly. Please try again later

**Comment by gaoyuan211** [comment]
again  again  again  ,but still again

**Comment by MicheleMonclova** [comment]
hi, can you tell us exactly what error you are getting?

**Comment by gaoyuan211** [comment]
i&nbsp; can&nbsp; not&nbsp; start&nbsp; the&nbsp; gpu or&nbsp; cpu&nbsp; &nbsp;mode



---Original---
From: ***@***.***&gt;
Date: Fri, Jan 14, 2022 13:08 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [aws/studio-lab-examples] no space ，and  can not start the project  ,how to solve the problem   (Issue #48)




 
hi, can you tell us exactly what error you are getting?
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by EmilyWebber** [comment]
Closing this for now due to lack of detail.
