### ISSUE TITLE
couldn't open Project on amazon sagemaker studio lab

### ISSUE THREAD

**Issue by saidineshpola** [aws/studio-lab-examples#52]
**Describe the bug**
Amazon Sagemaker studio lab is not opening jupyter notebook. It is loading indefinitely at Preparing project run time after that i am getting `There was a problem when starting the project runtime. This should be resolved shortly.` Please try again later. It's been almost a week and it still hasn't been resolved. Even though I tried shifting the runtime from CPU to GPU but issue still persists. Any help would be appreciated.

**The error i am getting is**
![image](https://user-images.githubusercontent.com/81302966/150034710-378eabbc-13fa-4820-adea-f2ebc8d66431.png)

**Comment by EmilyWebber** [comment]
Hi - sorry you're running into this issue, we're taking a look.

**Comment by lynfon** [comment]
I have also encountered this problem, which still exists at present.
![image](https://user-images.githubusercontent.com/37031974/150719178-b4b46fa6-d912-44e3-a412-f605435d664c.png)

**Comment by saidineshpola** [comment]
I deleted my account and re-created it, which took around 5 minutes for them to accept my request for the second time. If need instance then this is the only approach I could find. I had not received any updates from this issue after a week, so I recreated my instance.

**Comment by EmilyWebber** [comment]
I see - really sorry you're running into that. I've created a ticket with the team, but I'll close this issue for now since there is a known workaround.

**Comment by bsaha205** [comment]
Hello, I can't open project on amazon sagemaker. When I am clicking the 'open project' button, it is loading indefinitely, and I can't do anything with the files. I have restarted my project, browser, laptop, cleared cache, tried from other browsers, changed the env from GPU to CPU but nothing did work. Can you please take a look into my account and resolve the issue? Thanks!
