### ISSUE TITLE
cannnot download Large file such as 3.4G

### ISSUE THREAD

**Issue by hushuai1** [aws/studio-lab-examples#53]
cannnot download Large file such as 3.4G, there is no reply after click download the remaining time is enough.
![image](https://user-images.githubusercontent.com/43898397/151332712-a618c700-9034-4e90-8033-b87a501290d2.png)

**Comment by EmilyWebber** [comment]
Hi, sorry you ran into this issue. We're triaging. To get you unstuck in the meantime, do you have an AWS account? If you do, you could use the aws cli to copy that tar ball into your S3 bucket, then download it.

**Comment by samx18** [comment]
As we were testing this issue it seems that this behavior, i.e. download of large files getting stuck or crashing is not limited to SageMaker Studio Lab.  There seems to be common issue with JupyterLab and web browsers like chrome that cannot handle large file sizes. There is issue with JupyterLab [here](https://github.com/jupyter/notebook/issues/96)

**Comment by Ben-Yee** [comment]
The same issue occured to me.It took a long time to response my download request.If I try to copy the download link and paste ,the same issue occred.

**Comment by krassowski** [comment]
Just chiming in (not sure if its helpful) but enabling download of large files may require increasing `ServerApp.max_body_size` and `ServerApp.max_buffer_size` (assuming you use [jupyter-server](https://jupyter-server.readthedocs.io/en/latest/other/full-config.html)).

**Comment by pymia** [comment]
I've logged this issue in our internal ticket.
