### ISSUE TITLE
[BUG] "Open In in Sagemaker Studio Lab" button process fails when attempting to "Copy Notebooks Only"

### ISSUE THREAD

**Issue by taureandyernv** [aws/studio-lab-examples#54]
**Describe the bug**
Cloning a single notebook using the "Open In in Sagemaker Studio Lab" fails.  Cloning the whole repo works.  

Using sagemaker's sample, https://github.com/aws/studio-lab-examples/tree/main/open-in-studio-lab, I get this error:
```
Unable to copy notebook to project.
The link to this notebook is broken or blocked. If this is a private GitHub notebook, sign in to GitHub before copying the notebook.aws/studio-lab-examples/blob/main/natural-language-processing/NLP_Disaster_Recovery_Translation.ipynb
```
**To Reproduce**
1. create MD cell with `[![Open in SageMaker Studio Lab](https://studiolab.sagemaker.aws/studiolab.svg)](https://studiolab.sagemaker.aws/import/github/aws/studio-lab-examples/blob/main/natural-language-processing/NLP_Disaster_Recovery_Translation.ipynb)`  and run it
2. Click on the button that appears once you run the cell.  Will open new tab in browser
3. In the new pop up tab, click "Copy to Project".  Will open new tab in browser
4. In the new pop up tab's modal, select "Copy Notebook Only"
5. Error will now appear

**Expected behavior**
My notebook will open and appear, just as it would with cloning a directory

**Screenshots**
![image](https://user-images.githubusercontent.com/46935140/151415892-7d033f97-f98c-4ac8-9c50-99223253b1ee.png)

**Desktop (please complete the following information):**
 - OS: [Windows 11]
 - Browser [Chrome]
 - Version [97.0.4692.71]

**Comment by EmilyWebber** [comment]
Interesting - this works fine on my end, but I'm using a Mac. I'll create a ticket for you.

**Comment by zhimin-z** [comment]
[![xx](https://studiolab.sagemaker.aws/import/github/aws/studio-lab-examples/blob/main/natural-language-processing/NLP_Disaster_Recovery_Translation.ipynb)
