### ISSUE TITLE
Sagemaker Studio Lab: An error occurred. Please try again later.

### ISSUE THREAD

**Issue by AKwoKWH** [aws/studio-lab-examples#57]
**Describe the bug**
The lab have a error occur and unable to connect to my project runtime.

**To Reproduce**

1. Log into my account
2. See error message: "An error occurred. Please try again later."
(I tried log out and re-login again, still the same.)

**Expected behavior**
I expect I can load and start the project runtime on the web.

Screenshots
![image](https://user-images.githubusercontent.com/23435188/152629411-ca39398c-b5b0-4c39-abbe-3bfea43cd472.png)

**Comment by AKwoKWH** [comment]
[Update] I tried signout and signin again, it become the below:
![image](https://user-images.githubusercontent.com/23435188/152629566-fe5223f7-f880-4a50-8ae4-f5ef16808724.png)
I waited another 15min, the runtime is still preparing

**Comment by pymia** [comment]
Try to re-create the account. You can delete the account and re-create it.

**Comment by MicheleMonclova** [comment]
Please try again and tell us if you are still having any issues.
I don't think you need to delete account and recreate.

**Comment by AKwoKWH** [comment]
Update: it is auto fixed after some hours

**Comment by ioanfr** [comment]
We are glad to hear that. Let me close this issue for now.
Please reopen it if further assistance is needed. Thanks.
