### ISSUE TITLE
Stuck in 'Preparing project runtime..' after upgrade packages via conda

### ISSUE THREAD

**Issue by wenxhwork** [aws/studio-lab-examples#58]
**Describe the bug**
Stuck in 'Preparing project runtime..' for hours, no errors or extra information were reported in the browser.

**To Reproduce**
Not sure the following steps will reproduce, but I think they are of high probability.

1. Login studiolab
2. Choose GPU environment and run 'conda update --all' in terminal
3. End the environment
4. Choose GPU again and start environment

**Expected behavior**
The environment should be ready within minutes.

**Screenshots**
![1](https://user-images.githubusercontent.com/19337783/152630216-e15aa7a2-2708-4194-9bf8-bc9c2cd415ef.png)

**Desktop (please complete the following information):**
 - OS: Win10
 - Browser: Chrome
 - Version: 98.0.4758.82

**Additional context**
During upgrading, I noticed the package 'notebook' was updated and prompted a new version of conda.

**Comment by wenxhwork** [comment]
It's worked now. Close issue.

**Comment by NyanAung436** [comment]
@wenxhwork how did it work? I'm having the same issue

**Comment by wenxhwork** [comment]
@NyanAung436 Actually, I have no clue. I just waited for another hours before it worked.
