### ISSUE TITLE
help

### ISSUE THREAD

**Issue by hitam741** [aws/studio-lab-examples#60]
You have subscribed to
2/2/2022 So far my account has not been activated why

**Comment by MicheleMonclova** [comment]
hitam741, sorry for the delay, we are processing requests quickly. Please keep a look out for approvals in your inbox.

**Comment by icoxfog417** [comment]
Dear @hitam741 , do you still have the issue? If you already solved the problem, please close the issue.

**Comment by icoxfog417** [comment]
I close this issue. @hitam741, please let us know if your account is not approved yet.
