### ISSUE TITLE
Unexpected File Error After Large Dataset Download 

### ISSUE THREAD

**Issue by SamT6** [aws/studio-lab-examples#61]
**Describe the bug**
can't save, create, open, or delete any file on studio lab after trying to migrate around 10GB of data from AWS, an error happened midway (says no storage left), which stopped the data download. From then on I keep getting errors whenever I try to save, create, open, or delete files.

**To Reproduce**
Not sure how to reproduce the bug, I was able to successfully download a dataset with around the same size which I later delete, then when I try to download this 10GB dataset I get errors. 

**Expected behavior**
If there's no storage left, the data download stops and I should be able to delete files to free up storage instead of getting errors for any kind of file operations. 

**Screenshots**
<img width="600" alt="Screen Shot 2022-02-08 at 3 32 23 PM" src="https://user-images.githubusercontent.com/26547344/153070734-17d57bd8-c08f-4e33-9000-1884fccacd8b.png">
<img width="600" alt="Screen Shot 2022-02-08 at 3 34 24 PM" src="https://user-images.githubusercontent.com/26547344/153071019-0c7181fc-662d-4b12-a10c-dd749dff1c94.png">

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser: chrome
 - Version (unsure)

**Comment by samx18** [comment]
Hi , Can you check if you have any space left via the terminal using `df -h` . Also are you able to free up space by deleting the via the terminal directly?

**Comment by SamT6** [comment]
Hey thanks for the response. Yes it worked! I was able to free up space by deleting files via the terminal (with `rm -r <dir>`), and now I can again do any file operations. 

Another issue, however, is I couldn't seem to restore the storage to full capacity, after running `df -h`:
<img width="490" alt="Screen Shot 2022-02-11 at 9 30 18 AM" src="https://user-images.githubusercontent.com/26547344/153609851-10d5208e-c012-4503-99d7-726c725a0034.png">

which shows that there's only 3.9 GB available, while running `du -sh -- *` I get: 
<img width="404" alt="Screen Shot 2022-02-11 at 9 36 47 AM" src="https://user-images.githubusercontent.com/26547344/153610996-9442d045-2dfa-4791-9c4c-9be54adf05b2.png">

which shows that my files only take around 500 MB, my question is what used up the 22G of storage? I'm guessing it might be data regarding the variables ran in the notebooks, is there any way to delete or reset back to full capacity? 

Thank you!

**Comment by samx18** [comment]
Glad it worked. Yes, you can do a soft reset by deleting all the files and the `.conda` dir under home directory via the the terminal. After that log off and log back in. This is free up all the space.
