### ISSUE TITLE
after install ipykernel ,i still can't see the conda enviroment appear in the jupyter notebook or in luncher

### ISSUE THREAD

**Issue by awmmmm** [aws/studio-lab-examples#64]
**Describe the bug**
after install ipykernel ,i still can't see the conda enviroment appear in the jupyter notebook or in luncher.

**To Reproduce**
1. conda create a new env
2.conda install ipykernel
3. wait some time 
4. NO conda enviroment appear in the jupyter notebook or in luncher

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/89187860/153754635-a2271c31-c417-4147-8e4f-29122a828b96.png)
![image](https://user-images.githubusercontent.com/89187860/153754667-3a7ba821-92cc-419a-a615-fb4630abf853.png)

**Desktop (please complete the following information):**
 - OS: [e.g.win11]
 - Browser [ chrome]

**Additional context**

**Comment by awmmmm** [comment]
screen shot while choose kernel in notebook
![Uploading image.png…]()

**Comment by ioanfr** [comment]
Could you activate the new conda environment with conda activate command?
Also please share the output of the following command: conda env list

**Comment by awmmmm** [comment]
> 

yes,i can activate the new conda environment
![image](https://user-images.githubusercontent.com/89187860/154195290-ebc154d0-204b-4fe7-a062-ebda0a34304f.png)

**Comment by awmmmm** [comment]
> I do not see the new environment that you created in the list. These three environments are already preinstalled by default with the Studio Lab. Please have a look to this [sample notebook](https://github.com/aws/studio-lab-examples/blob/main/custom-environments/custom_environment.ipynb) for instructions on how to install a new environment. And you have more sample yaml files [here](https://github.com/aws/studio-lab-examples/tree/main/custom-environments).

cool ,thank you,i thought i can also see the three basic existing environment.now i create a new env with ipykernel and i can see  it in start page.
![image](https://user-images.githubusercontent.com/89187860/154411547-2c72e051-5971-42b6-8364-3c66576f7b2e.png)
