### ISSUE TITLE
Account request approved but on account registration not approved

### ISSUE THREAD

**Issue by GuiShenHe** [aws/studio-lab-examples#65]
I received an email titled "Account request approved" and a link to complete the registration last Firday(02/11/2022) and have since not been able to create an account.
I'm using the same email but continuously getting the error, "You haven’t been approved to create an account or your approval has expired. Please request an account."

I was told by a aws service representative to report the issue here.

**Comment by ioanfr** [comment]
GuiShenHe, apologies for the delay, we are processing requests quickly. Please keep a look out for approvals in your inbox.

**Comment by GuiShenHe** [comment]
> GuiShenHe, apologies for the delay, we are processing requests quickly. Please keep a look out for approvals in your inbox.

Should I re-request an account?

**Comment by darlyan** [comment]
Hi GuiShenHe,

Apologies for the experience you have been having so far.

Have you attempted to re-request an account with the same email? If you did so, you should have been re-sent a registration.

To aid in investigation, you may also pass your email through this tool and respond with the output SHA of your email address: https://emn178.github.io/online-tools/sha256.html

Thank you.

**Comment by icoxfog417** [comment]
Dear @GuiShenHe , do you still have the issue? If you already solve the problem, please close the issue.

**Comment by GuiShenHe** [comment]
@darlyan 7476619db4dec1d48cfbf3cedb0f724a96ffa8bd2f8cfe19aa8f28978de08821
@icoxfog417 I re-registered/requested with the same email over a month ago and I still have not received approval. I had assumed there was a long queue, but my friends seem to have gotten approval way quicker.

**Comment by icoxfog417** [comment]
Dear @GuiShenHe , I understood your long patience. Would you please refer #99 and submit the form? We can check the submitted information. At the same time please confirm your mailbox whether the approval email is sent or not.

**Comment by icoxfog417** [comment]
Dear @GuiShenHe , if your account is not approved yet, please let us know again. I close this issue.
