### ISSUE TITLE
Request to approve Sagemaker Studio Lab request for a Data science class

### ISSUE THREAD

**Issue by samrus98** [aws/studio-lab-examples#67]
Hello the wonderful team at Sagemaker Studio Lab! Thank you for making this free version available for the Data Science community! 

There are about 20 of us in a General Assembly data science class and we would love to use Sagemaker Studio Lab for the class if we can get our free account requests approved before next Wednesday 2/23. 

Here are the names of some of my classmates,  we realize you might have a huge backlog. Let us know if this is possible. Thanks!

**

**Comment by EmilyWebber** [comment]
Hello! Thanks for reaching out - to preserve anonymity I've removed your emails from the comment. However, we will do the best we can to approve your request.
