### ISSUE TITLE
I cannot "git push origin master"

### ISSUE THREAD

**Issue by diego26davila** [aws/studio-lab-examples#68]
Hi there, I wanted to git push a repository from Studio Lab but I got this errors : "error: cannot run ssh: No such file or directory
fatal: unable to fork" .

I was doing some searching and it seems i have to install ssh-client with apt-get, but I'm not allowed to (permission denied). What can I do? Hope you can help me.

**Comment by szamarin** [comment]
Are you able to use HTTP with a [personal access token ](https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/creating-a-personal-access-token) instead of SSH?

**Comment by diego26davila** [comment]
Yep! I could do it over HTTPS (I'm used to SSH that I forgot HTTPS). Thanks, @szamarin!
