### ISSUE TITLE
Unable to Connect to default:Python Kernel

### ISSUE THREAD

**Issue by jiayilong** [aws/studio-lab-examples#69]
Hi, it seems my default:Python kernel is completely down. I have used Sagemaker Lab for several days for training machine learning models, but this issue suddenly occurred today.

After I start the runtime, open an instance and open a notebook, the status bar on the bottom will show "default:Python | Connecting" for 1-2 mins, and then come with "default:Python | Disconnected". Finally, there will be "no kernel". 
![image](https://user-images.githubusercontent.com/92341385/154972686-f11563e4-2897-43b2-8752-168f775823af.png)

I made the following attempts, but the "connecting - disconnected" issue remains.
- Select the default Python kernel manually
- Open another notebook, even Getting Started.ipynb

I guess there is some wrong with the environment. May I know how to refresh the environment?

Thanks a lot for your help : )

**Comment by szamarin** [comment]
Are you able to access the terminal? If so, try running `conda activate default`, then `conda install --revision=0`. This should restore the environment to it's initial state

**Comment by jiayilong** [comment]
Hi @szamarin , thank you for your help. I tried to reset conda to reversion 0, but it did not work. So, I deleted my account and registered a new one. Luckly, the registration process took only a few minutes. Everything is fine now.
