### ISSUE TITLE
Jupyter notebook is not working

### ISSUE THREAD

**Issue by sallumandya1995** [aws/studio-lab-examples#70]
I have been using Studio lab for quite sometime , since yesterday i am unable to run python code in notebook ,
appreciate if your help in  troubleshooting / resetting the notebook

**Comment by Bimsbaby** [comment]
Can you try and restart the kernel and ensure that PyTorch Kernel is selected.

**Comment by icoxfog417** [comment]
@sallumandya1995 Would you please let us know your situation more in detail if you do not solve the problem now, Are there any error message when you try to run Python code?

**Comment by icoxfog417** [comment]
I close this issue because of no response. Dear @sallumandya1995 , if you sill have the problem, please do not hesitate to ask it by another issue.
