### ISSUE TITLE
ETA for waiting list on Amazon SageMaker Studio Lab

### ISSUE THREAD

**Issue by amakarewycz** [aws/studio-lab-examples#71]
Hi,  I submitted a request for a sagemaker lab account but I havent heard anything back beyond the confirmation that I'm on a wait list.  Its been a week, any hints on when I'll be off the wait list and the account will be made available?

**Comment by MicheleMonclova** [comment]
Hi, we have been processing a heavy demand, but we are adding more capacity and will approve you soon.

**Comment by amakarewycz** [comment]
got it today thanks!
