### ISSUE TITLE
Can't open project on amazon sagemaker

### ISSUE THREAD

**Issue by bsaha205** [aws/studio-lab-examples#72]
Hello, I can't open my project on amazon sagemaker. When I am clicking the 'open project' button, it is loading indefinitely, and I can't do anything with the files. I have restarted my project, browser, laptop, cleared cache, tried from other browsers, changed the env from GPU to CPU but nothing did work. Can you please take a look into my account and resolve the issue? A screenshot is attached here to understand better. Thanks!
<img width="1363" alt="Screen Shot 2022-02-22 at 9 45 35 PM" src="https://user-images.githubusercontent.com/12325889/155253679-bc27e42d-0a34-4e8d-8a08-7c1ad5fde9a8.png">

**Comment by MicheleMonclova** [comment]
Not sure if your issue has been resolved or not.
A quick fix is to delete your account and recreate. You will by pass the approval process if you use the same email that has already been approved.

**Comment by icoxfog417** [comment]
@bsaha205 do you still have the problem to open the project? Please let us know about your situation.

**Comment by icoxfog417** [comment]
I'll close the issue. If you have the trouble. please try @MicheleMonclova solution.

**Comment by bsaha205** [comment]
Hi @icoxfog417, yes the issue is resolved. Thanks.

**Comment by icoxfog417** [comment]
I am glad to hear that. Please enjoy your ML journey!
