### ISSUE TITLE
My account is not working.

### ISSUE THREAD

**Issue by CoffeeGiNu** [aws/studio-lab-examples#74]
I'm a student and I research on neural networks.
Today, I have "You can’t use the project runtime because your account is associated with activity that may have violated our Service Terms."
I have no idea what to do.
This is my first time to write in English. I'm sorry if there is something wrong. Please help me.

**Comment by MicheleMonclova** [comment]
Hi CoffeeGiNu - 
please fill in this form to explain your issue as well as tell us your SageMaker Lab log in: https://pages.awscloud.com/GLOBAL_PM_PA_amazon-sagemaker_20211116_7014z000000rjq2-registration.html

Thank you!
Michele

**Comment by icoxfog417** [comment]
Dear @CoffeeGiNu, did you submit us your situation from the form? Please let us know your situation to understand and solve your problem.

**Comment by icoxfog417** [comment]
Dear @CoffeeGiNu, do you still have issue? If not, please close this issue. If you still have the issue, please let us know.

**Comment by CoffeeGiNu** [comment]
> Dear @CoffeeGiNu, do you still have the issue? If not, please close this issue. If you still have the issue, please let us know.

Since there was nothing I could do, I deleted my account and applied again. Therefore, the account is already working properly.
However, there is still no announcement to me, as to why my account was suspended. I don't know the details of why.

Should I leave this issue open for others who have been suspended for similar reasons? If not necessary, I would like to close this.

**Comment by icoxfog417** [comment]
@CoffeeGiNu I relieved to hear your account is working properly. You can close this issue because we have same issues about it  and already have [FAQ section about violating](https://studiolab.sagemaker.aws/faq).
