### ISSUE TITLE
unable to generate ssh key

### ISSUE THREAD

**Issue by austinlasseter** [aws/studio-lab-examples#77]
I'd like to git clone using an ssh key instead of https. However, when I attempt the linux command ssh-keygen I get the following error message: bash: ssh-keygen: command not found

Is this expected behavior? Is it possible to install an ssh key on the Sagemaker instance? Thank you

**Comment by alaknan** [comment]
Please try  `conda install -c conda-forge openssh` to install ssh in studio lab and let us know if this resolves your issue.

**Comment by icoxfog417** [comment]
Dear @austinlasseter,  for now openssh is not installed initially. Does @alaknan solution help to solve the problem?

**Comment by austinlasseter** [comment]
Yes, this resolved the issue. Thank you.

**Comment by icoxfog417** [comment]
Dear @austinlasseter , thank you for your confirmation. If you ok, could you please close the issue ?

**Comment by austinlasseter** [comment]
Issue closed. Thank you.

**Comment by austinlasseter** [comment]
FWIW, I wrote up a tutorial about this, here: https://austinlasseter.medium.com/cloning-your-first-repo-to-amazon-sagemaker-studio-lab-992dc7a8c72

**Comment by icoxfog417** [comment]
@austinlasseter Thank you for your great article!
