### ISSUE TITLE
How to know storage utilization ?

### ISSUE THREAD

**Issue by diego26davila** [aws/studio-lab-examples#80]
Hi guys. Is there a way to know how many GB I have left before I reach the 15 GB limit?

**Comment by dr-natetorious** [comment]
Can you get this information from running in the terminal:
```bash
du -h -s /
```

**Comment by diego26davila** [comment]
Thanks @dr-natetorious it worked. But I had some permission denials. Do you know 

> Can you get this information from running in the terminal:
> 
> ```shell
> du -h -s /
> ```

Thanks @dr-natetorious it worked. But I got permission denials for some directories. Do you know if their bytes are included in the overall amount?

**Comment by dr-natetorious** [comment]
**Finalizing this thread**

The `du` command displays **disk usage** information. This example usage displays **statistics** in `-h`uman format for `-s`ubdirectories under `/`.

When you run this command through the terminal, it executes within a "safe security context". This context can't access specific OS-level ojects, and *likely will* print warnings to `stderr`.

These warnings are generally benign and can be ignored.

```sh
C:\Users\nateb>docker run -it debian bash
Unable to find image 'debian:latest' locally
latest: Pulling from library/debian
e4d61adff207: Pull complete
Digest: sha256:10b622c6cf6daa0a295be74c0e412ed20e10f91ae4c6f3ce6ff0c9c04f77cbf6
Status: Downloaded newer image for debian:latest
root@ff6b8427e147:/# du -h -s -s /
du: cannot access '/proc/8/task/8/fd/3': No such file or directory
du: cannot access '/proc/8/task/8/fdinfo/3': No such file or directory
du: cannot access '/proc/8/fd/4': No such file or directory
du: cannot access '/proc/8/fdinfo/4': No such file or directory
135M    /
root@ff6b8427e147:/# du -h -s -s / 2>/dev/null
135M    /
```
