### ISSUE TITLE
There is no response after requesting and verifying the email address！

### ISSUE THREAD

**Issue by Elibeau** [aws/studio-lab-examples#85]
Why is there no response after applying and verifying the email address

**Comment by MicheleMonclova** [comment]
After you request an account it needs to be approved.  Thank you for your patience. 
SageMaker Studio Lab Team

**Comment by icoxfog417** [comment]
Dear @Elibeau, do you still have issue of account approval? If not, please close this issue. If you still have the problem, please refer the #99 and follow the guidance on it.

**Comment by icoxfog417** [comment]
Dear @Elibeau , if your account is not approved yet, please let us know again. I close this issue.
