### ISSUE TITLE
Table of content - Jupyterlab Extension

### ISSUE THREAD

**Issue by ArnaudGlt** [aws/studio-lab-examples#86]
**Is your feature request related to a problem? Please describe.**
I would like to be able to use the jupyter-lab extension : @jupyterlab/toc-extension

It makes developing code and analysis a notebook in a jupyter-lab environment much more productive (instead of spending days scrolling up and down notebooks).

The version of jupyter-lab installed in my `SageMaker Studio` is 1.2.11

When I run the installation of the widget I get the following error:

> An error occurred installing @jupyterlab/toc-extension.
> 
> Error message:
> 
> No version of @jupyterlab/toc-extension could be found that is compatible with the current version of JupyterLab. However, it seems to support a new version of JupyterLab. Consider upgrading JupyterLab.
> 
> Conflicting Dependencies:
> JupyterLab              Extension       Package
> \>=1.2.11 <1.3.0         >=3.3.1 <4.0.0  @jupyterlab/application
> \>=1.2.11 <1.3.0         >=3.3.1 <4.0.0  @jupyterlab/docmanager
> \>=1.2.11 <1.3.0         >=3.3.1 <4.0.0  @jupyterlab/fileeditor
> \>=1.2.12 <1.3.0         >=3.3.1 <4.0.0  @jupyterlab/notebook
> \>=1.2.11 <1.3.0         >=3.3.1 <4.0.0  @jupyterlab/rendermime

**Describe the solution you'd like**
I would like to able to use the Table of Content as a tab on the left pane of the SageMaker Studio GUI.

Either propose a compatible installation procedure or allow user to upgrade jupyter-lab to version >=3

**Describe alternatives you've considered**
Not using SageMaker Studio but a custom jupyter-lab setup on a vanilla EC2 instance.

**Additional context**

**Comment by icoxfog417** [comment]
@AmaudGit, I understand that your request is showing the table of contents of the Jupyter Notebook. Did you try the vertical navigation menu? You can see the table of contents by clicking the following icon.

![image](https://user-images.githubusercontent.com/544269/158320854-e9e88c75-ab29-43b1-878e-d490c8e93cde.png)

**Comment by ArnaudGlt** [comment]
So I understood the problem, it is not related to Studio Lab, my bad. I was discovering the AWS universe, and it was confusing, they are 2 different services and 4 different features with almost the same names.

SageMaker Studio Lab: Free and Github community
SageMaker Studio: Paid service with 3 features:

Studio
Notebook - Jupyter (same as jupyter notebook)
Notebook - Jupyter Lab (same as jupyter lab)
For a Basic Support Plan, support on SageMaker AWS is inexistant. So, I came here following the doc on AWS.

All in all, I am closing this issue, as I realize that it doesn't target the right service. Sorry for that. I just want to say that at this time, Studio Lab (the free version), looks much more user friendly than the paid version Studio.
