### ISSUE TITLE
Connect to local file system

### ISSUE THREAD

**Issue by diego26davila** [aws/studio-lab-examples#87]
Hi there, I wrote a python script that creates a csv file and I want to save it in my local filesystem. Anybody knows how to do that without having to save it first in the Studio Lab storage and then download it to my local machine? Is there a way to connect the Jupyter environment to my local machine file system?

**Comment by icoxfog417** [comment]
@diego26davila Thank you for using the Studio Lab! I think you try to use Studio Lab as remote computing resource to create csv file.
At present, Studio Lab can not access your files without upload. As you indicated, you need to upload the Python script and create csv, then download it.
