### ISSUE TITLE
The GPU execution time never restart

### ISSUE THREAD

**Issue by MiguelRegueira** [aws/studio-lab-examples#88]
**Describe the bug**
The GPU execution time never restart. My user is mregueira. I have used GPU time once but it has never restarted, I'm not able to start a GPU session anymore. I have tried to eliminate the account and create it again, but the issue remains

**To Reproduce**
1. Select compute type GPU
2. Click on Start run time
3. There is no runtime available right now. Please change the compute type or try again later.

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/16226343/158352664-cb4501ef-931a-402a-9364-650098ed58ed.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser chrome

Thanks for your support,
Miguel

**Comment by magdiemad5s** [comment]
I've been using sage daily for my little fun projects, for 5 days I have never been able to get a GPU machine, tried a new account, and still do the same thing, i think it is not from our side but its from sage maker side,i hope they add more datacenters i think since they only use East Us 2 as i have seen in someone thread or something ,good luck getting a notebook with GPU i guess until they fix it

**Comment by MiguelRegueira** [comment]
Great to know, cannot complaint for a free service. If its lack of resources and not a bug that's it. It was weird for me that the first time I use it GPU worked but never again, but still it can be a coincidence.

**Comment by MicheleMonclova** [comment]
Thanks all for the feedback. We are working on making it more accessible and fair.

**Comment by lorazabora** [comment]
When will this issue get fixed? I can only get cpu runtimes

**Comment by austinlasseter** [comment]
Any update on when GPU's will be available again? I am teaching a data science class for a bootcamp, and all students are using Sagemaker Studio Lab. Without GPU's we can't train deep learning models. Greatly appreciate your making this service available free of charge - but is there a timeline on when it might be fixed? Thank you

**Comment by xor-128** [comment]
Yeah, its literally impossible to get GPU sesions...

**Comment by icoxfog417** [comment]
Dear @MiguelRegueira, we improved the GPU allocation recently. Could you please try launching the GPU instance ? (you do not need to recreate your account). If the problem solved, please let us know by closing this issue. We are very glad if we can support your working on your data science assignment.

**Comment by MiguelRegueira** [comment]
Thanks a lot! I've been able to start an execution on GPU. Closing the issue.

**Comment by RejwanShafi** [comment]
I have been also facing the problem I trained my model halfway yesterday and thought the remaining GPU time would restart today as well. After yesterday's training, I had only 45 mins left for GPU usage. WIll it get renewed today?

As I need more time to train the model efficiently and then validate and predict using my model?

![image](https://github.com/aws/studio-lab-examples/assets/147076527/2af8e635-601d-468e-a89a-6a4381fed734)
