### ISSUE TITLE
still waiting

### ISSUE THREAD

**Issue by kanlicali** [aws/studio-lab-examples#93]
It has been 2 weeks. Account still not confirmed. How long will we wait.

**Comment by lorazabora** [comment]
> It has been 2 weeks. Account still not confirmed. How long will we wait.

There are issues in the service right now, they probably won’t approve new accounts until it is solved

**Comment by kanlicali** [comment]
> 
My friends are using it. they don't have any problems.

what's the problem.

> > It has been 2 weeks. Account still not confirmed. How long will we wait.
> 
> There are issues in the service right now, they probably won’t approve new accounts until it is solved

**Comment by lorazabora** [comment]
Maybe they’re using it on CPU but there is a an issue with GPU

It logs “There is no runtime available now” error

**Comment by kanlicali** [comment]
I understand.

yes maybe they are using cpu. let them open the accounts bro. Shame on the CPU users. It has been 2 weeks. we are still waiting.


> Maybe they’re using it on CPU but there is a an issue with GPU
> 
> It logs “There is no runtime available now” error

**Comment by lorazabora** [comment]
There is no point in only using the CPU runtimes since there are many options out there that are far better and free as well, the special addition to the service is GPUS that also made it a strict-request system so it could meet the demand within the approved capacity and that’s what it seemed to be gladly, However I don’t believe that this issue has to do much with datacenters or demand because they manually choose and control the amount of users, it’s just a very bizarre issue im waiting for their reply

**Comment by lorazabora** [comment]
Otherwise if you were only looking to use CPUs it wouldn’t be much different than using Colab they pretty much give you 12 hours as well, I’d say do not bother unless you have models to be trained via GPUs since that’s what’s important in the service

**Comment by lorazabora** [comment]
It probably is, don’t worry about your approval just keep checking within the github here i posted the issue and there was some other guy as well who did but it was 5 days ago, the issue still remains and there isn’t much clarification regarding it yet

**Comment by kanlicali** [comment]
Will there be an explanation by sage?

**Comment by kanlicali** [comment]
@darlyan

**Comment by MicheleMonclova** [comment]
Hi Kanlicali, thank you for patience. I did try to add your email address that you have listed for github.  For security purposes do not send it to me here on github. Instead please fill out this form and we will try to expedite your request. 
https://pages.awscloud.com/GLOBAL_PM_PA_amazon-sagemaker_20211116_7014z000000rjq2-registration.html

**Comment by kanlicali** [comment]
I sent information.
@MicheleMonclova 

Should my other friends also fill out the form here?

Not many of my friends approved at school.

**Comment by kanlicali** [comment]
yes, my account approved 

thankk yo.

**Comment by kanlicali** [comment]
I've been waiting for a long time, write in the description section.

**Comment by icoxfog417** [comment]
Dear @kanlicali, thank you for patience. We want to migrate requests for account approval to #99. Please close this issue and 👍 to #99 issue if you do not mind. Of course, we are continuously dealing with your account.

**Comment by icoxfog417** [comment]
I close this issue. @kanlicali , I thought your account was approved in April. If you still have the trouble, feel free to raise a new issue.
