### ISSUE TITLE
Running Django on StudioLab

### ISSUE THREAD

**Issue by diego26davila** [aws/studio-lab-examples#97]
Hi there, is it possible to run Django server on Studio Lab? I want to connect via http://127.0.0.1:8000 but seems I can't get access. Anything I could do to connect?

**Comment by icoxfog417** [comment]
Dear @diego26davila Thank you for using the Studio Lab. Basically, Studio Lab only hosts the Jupyter Lab. I do not sure whether it enables to launch another port service, but TensorBoard seems to launch (#44 ). Can you try the following URL?

```
https://<YOUR_URL>.studio.us-east-2.sagemaker.aws/studiolab/default/jupyter/proxy/<YOUR_PORT>
```

If you have a request to add the feature to launch another port application, please raise a new feature request issue according to the [ISSUE_TEMPLATE](https://github.com/aws/studio-lab-examples/blob/main/.github/ISSUE_TEMPLATE/feature-request-for-sagemaker-studio-lab.md) .
If it is just the question, please confirm the answer and close this issue when you understand the specification of Studio Lab.

**Comment by icoxfog417** [comment]
I close this issue because of no response. Dear @diego26davila , I hope you launch the Django in Studio Lab!
